"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.JsBuiltinType = exports.StructureGroups = exports.StructureGroups_StructureGroup = exports.Module = exports.Module_Which = exports.Constructor = exports.Constant = exports.Property = exports.Method = exports.Member = exports.Member_Which = exports.Member_Nested = exports.Structure = exports.JsgImplType = exports.JsgImplType_Type = exports.FunctionType = exports.BuiltinType = exports.BuiltinType_Type = exports.OneOfType = exports.DictType = exports.MaybeType = exports.ArrayType = exports.IntrinsicType = exports.StringType = exports.StructureType = exports.PromiseType = exports.NumberType = exports.Type = exports.Type_Which = exports._capnpFileId = void 0;
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "b042d6da9e1721ad";
var Type_Which;
(function (Type_Which) {
    Type_Which[Type_Which["UNKNOWN"] = 0] = "UNKNOWN";
    Type_Which[Type_Which["VOIDT"] = 1] = "VOIDT";
    Type_Which[Type_Which["BOOLT"] = 2] = "BOOLT";
    Type_Which[Type_Which["NUMBER"] = 3] = "NUMBER";
    Type_Which[Type_Which["PROMISE"] = 4] = "PROMISE";
    Type_Which[Type_Which["STRUCTURE"] = 5] = "STRUCTURE";
    Type_Which[Type_Which["STRING"] = 6] = "STRING";
    Type_Which[Type_Which["OBJECT"] = 7] = "OBJECT";
    Type_Which[Type_Which["ARRAY"] = 8] = "ARRAY";
    Type_Which[Type_Which["MAYBE"] = 9] = "MAYBE";
    Type_Which[Type_Which["DICT"] = 10] = "DICT";
    Type_Which[Type_Which["ONE_OF"] = 11] = "ONE_OF";
    Type_Which[Type_Which["BUILTIN"] = 12] = "BUILTIN";
    Type_Which[Type_Which["INTRINSIC"] = 13] = "INTRINSIC";
    Type_Which[Type_Which["FUNCTION"] = 14] = "FUNCTION";
    Type_Which[Type_Which["JSG_IMPL"] = 15] = "JSG_IMPL";
    Type_Which[Type_Which["JS_BUILTIN"] = 16] = "JS_BUILTIN";
})(Type_Which = exports.Type_Which || (exports.Type_Which = {}));
class Type extends capnp_ts_1.Struct {
    isUnknown() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setUnknown() { capnp_ts_1.Struct.setUint16(0, 0, this); }
    isVoidt() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setVoidt() { capnp_ts_1.Struct.setUint16(0, 1, this); }
    isBoolt() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setBoolt() { capnp_ts_1.Struct.setUint16(0, 2, this); }
    adoptNumber(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownNumber() { return capnp_ts_1.Struct.disown(this.getNumber()); }
    getNumber() {
        capnp_ts_1.Struct.testWhich("number", capnp_ts_1.Struct.getUint16(0, this), 3, this);
        return capnp_ts_1.Struct.getStruct(0, NumberType, this);
    }
    hasNumber() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initNumber() {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        return capnp_ts_1.Struct.initStructAt(0, NumberType, this);
    }
    isNumber() { return capnp_ts_1.Struct.getUint16(0, this) === 3; }
    setNumber(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptPromise(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownPromise() { return capnp_ts_1.Struct.disown(this.getPromise()); }
    getPromise() {
        capnp_ts_1.Struct.testWhich("promise", capnp_ts_1.Struct.getUint16(0, this), 4, this);
        return capnp_ts_1.Struct.getStruct(0, PromiseType, this);
    }
    hasPromise() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initPromise() {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        return capnp_ts_1.Struct.initStructAt(0, PromiseType, this);
    }
    isPromise() { return capnp_ts_1.Struct.getUint16(0, this) === 4; }
    setPromise(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptStructure(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownStructure() { return capnp_ts_1.Struct.disown(this.getStructure()); }
    getStructure() {
        capnp_ts_1.Struct.testWhich("structure", capnp_ts_1.Struct.getUint16(0, this), 5, this);
        return capnp_ts_1.Struct.getStruct(0, StructureType, this);
    }
    hasStructure() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initStructure() {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        return capnp_ts_1.Struct.initStructAt(0, StructureType, this);
    }
    isStructure() { return capnp_ts_1.Struct.getUint16(0, this) === 5; }
    setStructure(value) {
        capnp_ts_1.Struct.setUint16(0, 5, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptString(value) {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownString() { return capnp_ts_1.Struct.disown(this.getString()); }
    getString() {
        capnp_ts_1.Struct.testWhich("string", capnp_ts_1.Struct.getUint16(0, this), 6, this);
        return capnp_ts_1.Struct.getStruct(0, StringType, this);
    }
    hasString() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initString() {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        return capnp_ts_1.Struct.initStructAt(0, StringType, this);
    }
    isString() { return capnp_ts_1.Struct.getUint16(0, this) === 6; }
    setString(value) {
        capnp_ts_1.Struct.setUint16(0, 6, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    isObject() { return capnp_ts_1.Struct.getUint16(0, this) === 7; }
    setObject() { capnp_ts_1.Struct.setUint16(0, 7, this); }
    adoptArray(value) {
        capnp_ts_1.Struct.setUint16(0, 8, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownArray() { return capnp_ts_1.Struct.disown(this.getArray()); }
    getArray() {
        capnp_ts_1.Struct.testWhich("array", capnp_ts_1.Struct.getUint16(0, this), 8, this);
        return capnp_ts_1.Struct.getStruct(0, ArrayType, this);
    }
    hasArray() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initArray() {
        capnp_ts_1.Struct.setUint16(0, 8, this);
        return capnp_ts_1.Struct.initStructAt(0, ArrayType, this);
    }
    isArray() { return capnp_ts_1.Struct.getUint16(0, this) === 8; }
    setArray(value) {
        capnp_ts_1.Struct.setUint16(0, 8, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptMaybe(value) {
        capnp_ts_1.Struct.setUint16(0, 9, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownMaybe() { return capnp_ts_1.Struct.disown(this.getMaybe()); }
    getMaybe() {
        capnp_ts_1.Struct.testWhich("maybe", capnp_ts_1.Struct.getUint16(0, this), 9, this);
        return capnp_ts_1.Struct.getStruct(0, MaybeType, this);
    }
    hasMaybe() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMaybe() {
        capnp_ts_1.Struct.setUint16(0, 9, this);
        return capnp_ts_1.Struct.initStructAt(0, MaybeType, this);
    }
    isMaybe() { return capnp_ts_1.Struct.getUint16(0, this) === 9; }
    setMaybe(value) {
        capnp_ts_1.Struct.setUint16(0, 9, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptDict(value) {
        capnp_ts_1.Struct.setUint16(0, 10, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownDict() { return capnp_ts_1.Struct.disown(this.getDict()); }
    getDict() {
        capnp_ts_1.Struct.testWhich("dict", capnp_ts_1.Struct.getUint16(0, this), 10, this);
        return capnp_ts_1.Struct.getStruct(0, DictType, this);
    }
    hasDict() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initDict() {
        capnp_ts_1.Struct.setUint16(0, 10, this);
        return capnp_ts_1.Struct.initStructAt(0, DictType, this);
    }
    isDict() { return capnp_ts_1.Struct.getUint16(0, this) === 10; }
    setDict(value) {
        capnp_ts_1.Struct.setUint16(0, 10, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptOneOf(value) {
        capnp_ts_1.Struct.setUint16(0, 11, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownOneOf() { return capnp_ts_1.Struct.disown(this.getOneOf()); }
    getOneOf() {
        capnp_ts_1.Struct.testWhich("oneOf", capnp_ts_1.Struct.getUint16(0, this), 11, this);
        return capnp_ts_1.Struct.getStruct(0, OneOfType, this);
    }
    hasOneOf() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initOneOf() {
        capnp_ts_1.Struct.setUint16(0, 11, this);
        return capnp_ts_1.Struct.initStructAt(0, OneOfType, this);
    }
    isOneOf() { return capnp_ts_1.Struct.getUint16(0, this) === 11; }
    setOneOf(value) {
        capnp_ts_1.Struct.setUint16(0, 11, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptBuiltin(value) {
        capnp_ts_1.Struct.setUint16(0, 12, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownBuiltin() { return capnp_ts_1.Struct.disown(this.getBuiltin()); }
    getBuiltin() {
        capnp_ts_1.Struct.testWhich("builtin", capnp_ts_1.Struct.getUint16(0, this), 12, this);
        return capnp_ts_1.Struct.getStruct(0, BuiltinType, this);
    }
    hasBuiltin() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initBuiltin() {
        capnp_ts_1.Struct.setUint16(0, 12, this);
        return capnp_ts_1.Struct.initStructAt(0, BuiltinType, this);
    }
    isBuiltin() { return capnp_ts_1.Struct.getUint16(0, this) === 12; }
    setBuiltin(value) {
        capnp_ts_1.Struct.setUint16(0, 12, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptIntrinsic(value) {
        capnp_ts_1.Struct.setUint16(0, 13, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownIntrinsic() { return capnp_ts_1.Struct.disown(this.getIntrinsic()); }
    getIntrinsic() {
        capnp_ts_1.Struct.testWhich("intrinsic", capnp_ts_1.Struct.getUint16(0, this), 13, this);
        return capnp_ts_1.Struct.getStruct(0, IntrinsicType, this);
    }
    hasIntrinsic() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initIntrinsic() {
        capnp_ts_1.Struct.setUint16(0, 13, this);
        return capnp_ts_1.Struct.initStructAt(0, IntrinsicType, this);
    }
    isIntrinsic() { return capnp_ts_1.Struct.getUint16(0, this) === 13; }
    setIntrinsic(value) {
        capnp_ts_1.Struct.setUint16(0, 13, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptFunction(value) {
        capnp_ts_1.Struct.setUint16(0, 14, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownFunction() { return capnp_ts_1.Struct.disown(this.getFunction()); }
    getFunction() {
        capnp_ts_1.Struct.testWhich("function", capnp_ts_1.Struct.getUint16(0, this), 14, this);
        return capnp_ts_1.Struct.getStruct(0, FunctionType, this);
    }
    hasFunction() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initFunction() {
        capnp_ts_1.Struct.setUint16(0, 14, this);
        return capnp_ts_1.Struct.initStructAt(0, FunctionType, this);
    }
    isFunction() { return capnp_ts_1.Struct.getUint16(0, this) === 14; }
    setFunction(value) {
        capnp_ts_1.Struct.setUint16(0, 14, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptJsgImpl(value) {
        capnp_ts_1.Struct.setUint16(0, 15, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownJsgImpl() { return capnp_ts_1.Struct.disown(this.getJsgImpl()); }
    getJsgImpl() {
        capnp_ts_1.Struct.testWhich("jsgImpl", capnp_ts_1.Struct.getUint16(0, this), 15, this);
        return capnp_ts_1.Struct.getStruct(0, JsgImplType, this);
    }
    hasJsgImpl() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initJsgImpl() {
        capnp_ts_1.Struct.setUint16(0, 15, this);
        return capnp_ts_1.Struct.initStructAt(0, JsgImplType, this);
    }
    isJsgImpl() { return capnp_ts_1.Struct.getUint16(0, this) === 15; }
    setJsgImpl(value) {
        capnp_ts_1.Struct.setUint16(0, 15, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptJsBuiltin(value) {
        capnp_ts_1.Struct.setUint16(0, 16, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownJsBuiltin() { return capnp_ts_1.Struct.disown(this.getJsBuiltin()); }
    getJsBuiltin() {
        capnp_ts_1.Struct.testWhich("jsBuiltin", capnp_ts_1.Struct.getUint16(0, this), 16, this);
        return capnp_ts_1.Struct.getStruct(0, JsBuiltinType, this);
    }
    hasJsBuiltin() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initJsBuiltin() {
        capnp_ts_1.Struct.setUint16(0, 16, this);
        return capnp_ts_1.Struct.initStructAt(0, JsBuiltinType, this);
    }
    isJsBuiltin() { return capnp_ts_1.Struct.getUint16(0, this) === 16; }
    setJsBuiltin(value) {
        capnp_ts_1.Struct.setUint16(0, 16, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    toString() { return "Type_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Type = Type;
Type.UNKNOWN = Type_Which.UNKNOWN;
Type.VOIDT = Type_Which.VOIDT;
Type.BOOLT = Type_Which.BOOLT;
Type.NUMBER = Type_Which.NUMBER;
Type.PROMISE = Type_Which.PROMISE;
Type.STRUCTURE = Type_Which.STRUCTURE;
Type.STRING = Type_Which.STRING;
Type.OBJECT = Type_Which.OBJECT;
Type.ARRAY = Type_Which.ARRAY;
Type.MAYBE = Type_Which.MAYBE;
Type.DICT = Type_Which.DICT;
Type.ONE_OF = Type_Which.ONE_OF;
Type.BUILTIN = Type_Which.BUILTIN;
Type.INTRINSIC = Type_Which.INTRINSIC;
Type.FUNCTION = Type_Which.FUNCTION;
Type.JSG_IMPL = Type_Which.JSG_IMPL;
Type.JS_BUILTIN = Type_Which.JS_BUILTIN;
Type._capnp = { displayName: "Type", id: "d2347ab301451a8c", size: new capnp_ts_1.ObjectSize(8, 1) };
class NumberType extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    toString() { return "NumberType_" + super.toString(); }
}
exports.NumberType = NumberType;
NumberType._capnp = { displayName: "NumberType", id: "afd4316863bdd80a", size: new capnp_ts_1.ObjectSize(0, 1) };
class PromiseType extends capnp_ts_1.Struct {
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getStruct(0, Type, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initValue() { return capnp_ts_1.Struct.initStructAt(0, Type, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "PromiseType_" + super.toString(); }
}
exports.PromiseType = PromiseType;
PromiseType._capnp = { displayName: "PromiseType", id: "977eaa74d24bb2dc", size: new capnp_ts_1.ObjectSize(0, 1) };
class StructureType extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getFullyQualifiedName() { return capnp_ts_1.Struct.getText(1, this); }
    setFullyQualifiedName(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "StructureType_" + super.toString(); }
}
exports.StructureType = StructureType;
StructureType._capnp = { displayName: "StructureType", id: "9001b3522132305a", size: new capnp_ts_1.ObjectSize(0, 2) };
class StringType extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    toString() { return "StringType_" + super.toString(); }
}
exports.StringType = StringType;
StringType._capnp = { displayName: "StringType", id: "913621db0713d640", size: new capnp_ts_1.ObjectSize(0, 1) };
class IntrinsicType extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    toString() { return "IntrinsicType_" + super.toString(); }
}
exports.IntrinsicType = IntrinsicType;
IntrinsicType._capnp = { displayName: "IntrinsicType", id: "87c24648e89ccc02", size: new capnp_ts_1.ObjectSize(0, 1) };
class ArrayType extends capnp_ts_1.Struct {
    adoptElement(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownElement() { return capnp_ts_1.Struct.disown(this.getElement()); }
    getElement() { return capnp_ts_1.Struct.getStruct(0, Type, this); }
    hasElement() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initElement() { return capnp_ts_1.Struct.initStructAt(0, Type, this); }
    setElement(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getName() { return capnp_ts_1.Struct.getText(1, this); }
    setName(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "ArrayType_" + super.toString(); }
}
exports.ArrayType = ArrayType;
ArrayType._capnp = { displayName: "ArrayType", id: "f6d86da0d225932b", size: new capnp_ts_1.ObjectSize(0, 2) };
class MaybeType extends capnp_ts_1.Struct {
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getStruct(0, Type, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initValue() { return capnp_ts_1.Struct.initStructAt(0, Type, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getName() { return capnp_ts_1.Struct.getText(1, this); }
    setName(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "MaybeType_" + super.toString(); }
}
exports.MaybeType = MaybeType;
MaybeType._capnp = { displayName: "MaybeType", id: "9d64649bff8a5cee", size: new capnp_ts_1.ObjectSize(0, 2) };
class DictType extends capnp_ts_1.Struct {
    adoptKey(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKey() { return capnp_ts_1.Struct.disown(this.getKey()); }
    getKey() { return capnp_ts_1.Struct.getStruct(0, Type, this); }
    hasKey() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKey() { return capnp_ts_1.Struct.initStructAt(0, Type, this); }
    setKey(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptValue(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownValue() { return capnp_ts_1.Struct.disown(this.getValue()); }
    getValue() { return capnp_ts_1.Struct.getStruct(1, Type, this); }
    hasValue() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initValue() { return capnp_ts_1.Struct.initStructAt(1, Type, this); }
    setValue(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "DictType_" + super.toString(); }
}
exports.DictType = DictType;
DictType._capnp = { displayName: "DictType", id: "b7d8e1ee6205d554", size: new capnp_ts_1.ObjectSize(0, 2) };
class OneOfType extends capnp_ts_1.Struct {
    adoptVariants(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownVariants() { return capnp_ts_1.Struct.disown(this.getVariants()); }
    getVariants() { return capnp_ts_1.Struct.getList(0, OneOfType._Variants, this); }
    hasVariants() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initVariants(length) { return capnp_ts_1.Struct.initList(0, OneOfType._Variants, length, this); }
    setVariants(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "OneOfType_" + super.toString(); }
}
exports.OneOfType = OneOfType;
OneOfType._capnp = { displayName: "OneOfType", id: "95216521d1f195ae", size: new capnp_ts_1.ObjectSize(0, 1) };
var BuiltinType_Type;
(function (BuiltinType_Type) {
    BuiltinType_Type[BuiltinType_Type["V8UINT8ARRAY"] = 0] = "V8UINT8ARRAY";
    BuiltinType_Type[BuiltinType_Type["V8ARRAY_BUFFER_VIEW"] = 1] = "V8ARRAY_BUFFER_VIEW";
    BuiltinType_Type[BuiltinType_Type["JSG_BUFFER_SOURCE"] = 2] = "JSG_BUFFER_SOURCE";
    BuiltinType_Type[BuiltinType_Type["KJ_DATE"] = 3] = "KJ_DATE";
    BuiltinType_Type[BuiltinType_Type["V8FUNCTION"] = 4] = "V8FUNCTION";
    BuiltinType_Type[BuiltinType_Type["V8ARRAY_BUFFER"] = 5] = "V8ARRAY_BUFFER";
})(BuiltinType_Type = exports.BuiltinType_Type || (exports.BuiltinType_Type = {}));
class BuiltinType extends capnp_ts_1.Struct {
    getType() { return capnp_ts_1.Struct.getUint16(0, this); }
    setType(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    toString() { return "BuiltinType_" + super.toString(); }
}
exports.BuiltinType = BuiltinType;
BuiltinType.Type = BuiltinType_Type;
BuiltinType._capnp = { displayName: "BuiltinType", id: "96dfb79b276b3379", size: new capnp_ts_1.ObjectSize(8, 0) };
class FunctionType extends capnp_ts_1.Struct {
    adoptReturnType(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownReturnType() { return capnp_ts_1.Struct.disown(this.getReturnType()); }
    getReturnType() { return capnp_ts_1.Struct.getStruct(0, Type, this); }
    hasReturnType() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initReturnType() { return capnp_ts_1.Struct.initStructAt(0, Type, this); }
    setReturnType(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptArgs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownArgs() { return capnp_ts_1.Struct.disown(this.getArgs()); }
    getArgs() { return capnp_ts_1.Struct.getList(1, FunctionType._Args, this); }
    hasArgs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initArgs(length) { return capnp_ts_1.Struct.initList(1, FunctionType._Args, length, this); }
    setArgs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "FunctionType_" + super.toString(); }
}
exports.FunctionType = FunctionType;
FunctionType._capnp = { displayName: "FunctionType", id: "d7c3505ac05e5fad", size: new capnp_ts_1.ObjectSize(0, 2) };
var JsgImplType_Type;
(function (JsgImplType_Type) {
    JsgImplType_Type[JsgImplType_Type["CONFIGURATION"] = 0] = "CONFIGURATION";
    JsgImplType_Type[JsgImplType_Type["V8ISOLATE"] = 1] = "V8ISOLATE";
    JsgImplType_Type[JsgImplType_Type["JSG_LOCK"] = 2] = "JSG_LOCK";
    JsgImplType_Type[JsgImplType_Type["JSG_TYPE_HANDLER"] = 3] = "JSG_TYPE_HANDLER";
    JsgImplType_Type[JsgImplType_Type["JSG_UNIMPLEMENTED"] = 4] = "JSG_UNIMPLEMENTED";
    JsgImplType_Type[JsgImplType_Type["JSG_VARARGS"] = 5] = "JSG_VARARGS";
    JsgImplType_Type[JsgImplType_Type["JSG_SELF_REF"] = 6] = "JSG_SELF_REF";
    JsgImplType_Type[JsgImplType_Type["V8FUNCTION_CALLBACK_INFO"] = 7] = "V8FUNCTION_CALLBACK_INFO";
    JsgImplType_Type[JsgImplType_Type["V8PROPERTY_CALLBACK_INFO"] = 8] = "V8PROPERTY_CALLBACK_INFO";
    JsgImplType_Type[JsgImplType_Type["JSG_NAME"] = 9] = "JSG_NAME";
})(JsgImplType_Type = exports.JsgImplType_Type || (exports.JsgImplType_Type = {}));
class JsgImplType extends capnp_ts_1.Struct {
    getType() { return capnp_ts_1.Struct.getUint16(0, this); }
    setType(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    toString() { return "JsgImplType_" + super.toString(); }
}
exports.JsgImplType = JsgImplType;
JsgImplType.Type = JsgImplType_Type;
JsgImplType._capnp = { displayName: "JsgImplType", id: "e0dfbe1216e6985e", size: new capnp_ts_1.ObjectSize(8, 0) };
class Structure extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getFullyQualifiedName() { return capnp_ts_1.Struct.getText(3, this); }
    setFullyQualifiedName(value) { capnp_ts_1.Struct.setText(3, value, this); }
    adoptMembers(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownMembers() { return capnp_ts_1.Struct.disown(this.getMembers()); }
    getMembers() { return capnp_ts_1.Struct.getList(1, Structure._Members, this); }
    hasMembers() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initMembers(length) { return capnp_ts_1.Struct.initList(1, Structure._Members, length, this); }
    setMembers(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptExtends(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownExtends() { return capnp_ts_1.Struct.disown(this.getExtends()); }
    getExtends() { return capnp_ts_1.Struct.getStruct(2, Type, this); }
    hasExtends() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initExtends() { return capnp_ts_1.Struct.initStructAt(2, Type, this); }
    setExtends(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    getIterable() { return capnp_ts_1.Struct.getBit(0, this); }
    setIterable(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    adoptIterator(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownIterator() { return capnp_ts_1.Struct.disown(this.getIterator()); }
    getIterator() { return capnp_ts_1.Struct.getStruct(4, Method, this); }
    hasIterator() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initIterator() { return capnp_ts_1.Struct.initStructAt(4, Method, this); }
    setIterator(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    getAsyncIterable() { return capnp_ts_1.Struct.getBit(1, this); }
    setAsyncIterable(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    adoptAsyncIterator(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownAsyncIterator() { return capnp_ts_1.Struct.disown(this.getAsyncIterator()); }
    getAsyncIterator() { return capnp_ts_1.Struct.getStruct(5, Method, this); }
    hasAsyncIterator() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initAsyncIterator() { return capnp_ts_1.Struct.initStructAt(5, Method, this); }
    setAsyncIterator(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    getTsRoot() { return capnp_ts_1.Struct.getBit(2, this); }
    setTsRoot(value) { capnp_ts_1.Struct.setBit(2, value, this); }
    getTsOverride() { return capnp_ts_1.Struct.getText(6, this); }
    setTsOverride(value) { capnp_ts_1.Struct.setText(6, value, this); }
    getTsDefine() { return capnp_ts_1.Struct.getText(7, this); }
    setTsDefine(value) { capnp_ts_1.Struct.setText(7, value, this); }
    adoptCallable(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(8, this)); }
    disownCallable() { return capnp_ts_1.Struct.disown(this.getCallable()); }
    getCallable() { return capnp_ts_1.Struct.getStruct(8, FunctionType, this); }
    hasCallable() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(8, this)); }
    initCallable() { return capnp_ts_1.Struct.initStructAt(8, FunctionType, this); }
    setCallable(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(8, this)); }
    adoptBuiltinModules(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(9, this)); }
    disownBuiltinModules() { return capnp_ts_1.Struct.disown(this.getBuiltinModules()); }
    getBuiltinModules() { return capnp_ts_1.Struct.getList(9, Structure._BuiltinModules, this); }
    hasBuiltinModules() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(9, this)); }
    initBuiltinModules(length) { return capnp_ts_1.Struct.initList(9, Structure._BuiltinModules, length, this); }
    setBuiltinModules(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(9, this)); }
    toString() { return "Structure_" + super.toString(); }
}
exports.Structure = Structure;
Structure._capnp = { displayName: "Structure", id: "c9aee5d3d27484f2", size: new capnp_ts_1.ObjectSize(8, 10) };
class Member_Nested extends capnp_ts_1.Struct {
    adoptStructure(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownStructure() { return capnp_ts_1.Struct.disown(this.getStructure()); }
    getStructure() { return capnp_ts_1.Struct.getStruct(0, Structure, this); }
    hasStructure() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initStructure() { return capnp_ts_1.Struct.initStructAt(0, Structure, this); }
    setStructure(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getName() { return capnp_ts_1.Struct.getText(1, this); }
    setName(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "Member_Nested_" + super.toString(); }
}
exports.Member_Nested = Member_Nested;
Member_Nested._capnp = { displayName: "nested", id: "cc1920702876b1f6", size: new capnp_ts_1.ObjectSize(8, 2) };
var Member_Which;
(function (Member_Which) {
    Member_Which[Member_Which["METHOD"] = 0] = "METHOD";
    Member_Which[Member_Which["PROPERTY"] = 1] = "PROPERTY";
    Member_Which[Member_Which["NESTED"] = 2] = "NESTED";
    Member_Which[Member_Which["CONSTANT"] = 3] = "CONSTANT";
    Member_Which[Member_Which["CONSTRUCTOR"] = 4] = "CONSTRUCTOR";
})(Member_Which = exports.Member_Which || (exports.Member_Which = {}));
class Member extends capnp_ts_1.Struct {
    adoptMethod(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownMethod() { return capnp_ts_1.Struct.disown(this.getMethod()); }
    getMethod() {
        capnp_ts_1.Struct.testWhich("method", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getStruct(0, Method, this);
    }
    hasMethod() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initMethod() {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initStructAt(0, Method, this);
    }
    isMethod() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setMethod(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptProperty(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownProperty() { return capnp_ts_1.Struct.disown(this.getProperty()); }
    getProperty() {
        capnp_ts_1.Struct.testWhich("property", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getStruct(0, Property, this);
    }
    hasProperty() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initProperty() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.initStructAt(0, Property, this);
    }
    isProperty() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setProperty(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    getNested() {
        capnp_ts_1.Struct.testWhich("nested", capnp_ts_1.Struct.getUint16(0, this), 2, this);
        return capnp_ts_1.Struct.getAs(Member_Nested, this);
    }
    initNested() {
        capnp_ts_1.Struct.setUint16(0, 2, this);
        return capnp_ts_1.Struct.getAs(Member_Nested, this);
    }
    isNested() { return capnp_ts_1.Struct.getUint16(0, this) === 2; }
    setNested() { capnp_ts_1.Struct.setUint16(0, 2, this); }
    adoptConstant(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownConstant() { return capnp_ts_1.Struct.disown(this.getConstant()); }
    getConstant() {
        capnp_ts_1.Struct.testWhich("constant", capnp_ts_1.Struct.getUint16(0, this), 3, this);
        return capnp_ts_1.Struct.getStruct(0, Constant, this);
    }
    hasConstant() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initConstant() {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        return capnp_ts_1.Struct.initStructAt(0, Constant, this);
    }
    isConstant() { return capnp_ts_1.Struct.getUint16(0, this) === 3; }
    setConstant(value) {
        capnp_ts_1.Struct.setUint16(0, 3, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptConstructor(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownConstructor() { return capnp_ts_1.Struct.disown(this.getConstructor()); }
    getConstructor() {
        capnp_ts_1.Struct.testWhich("constructor", capnp_ts_1.Struct.getUint16(0, this), 4, this);
        return capnp_ts_1.Struct.getStruct(0, Constructor, this);
    }
    hasConstructor() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initConstructor() {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        return capnp_ts_1.Struct.initStructAt(0, Constructor, this);
    }
    isConstructor() { return capnp_ts_1.Struct.getUint16(0, this) === 4; }
    setConstructor(value) {
        capnp_ts_1.Struct.setUint16(0, 4, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    toString() { return "Member_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Member = Member;
Member.METHOD = Member_Which.METHOD;
Member.PROPERTY = Member_Which.PROPERTY;
Member.NESTED = Member_Which.NESTED;
Member.CONSTANT = Member_Which.CONSTANT;
Member.CONSTRUCTOR = Member_Which.CONSTRUCTOR;
Member._capnp = { displayName: "Member", id: "85c316fd4114aba7", size: new capnp_ts_1.ObjectSize(8, 2) };
class Method extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptReturnType(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownReturnType() { return capnp_ts_1.Struct.disown(this.getReturnType()); }
    getReturnType() { return capnp_ts_1.Struct.getStruct(1, Type, this); }
    hasReturnType() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initReturnType() { return capnp_ts_1.Struct.initStructAt(1, Type, this); }
    setReturnType(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptArgs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownArgs() { return capnp_ts_1.Struct.disown(this.getArgs()); }
    getArgs() { return capnp_ts_1.Struct.getList(2, Method._Args, this); }
    hasArgs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initArgs(length) { return capnp_ts_1.Struct.initList(2, Method._Args, length, this); }
    setArgs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    getStatic() { return capnp_ts_1.Struct.getBit(0, this); }
    setStatic(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    toString() { return "Method_" + super.toString(); }
}
exports.Method = Method;
Method._capnp = { displayName: "Method", id: "a0a20f19ed7321e8", size: new capnp_ts_1.ObjectSize(8, 3) };
class Property extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptType(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownType() { return capnp_ts_1.Struct.disown(this.getType()); }
    getType() { return capnp_ts_1.Struct.getStruct(1, Type, this); }
    hasType() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initType() { return capnp_ts_1.Struct.initStructAt(1, Type, this); }
    setType(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getReadonly() { return capnp_ts_1.Struct.getBit(0, this); }
    setReadonly(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getLazy() { return capnp_ts_1.Struct.getBit(1, this); }
    setLazy(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    getPrototype() { return capnp_ts_1.Struct.getBit(2, this); }
    setPrototype(value) { capnp_ts_1.Struct.setBit(2, value, this); }
    toString() { return "Property_" + super.toString(); }
}
exports.Property = Property;
Property._capnp = { displayName: "Property", id: "e1d238e9fecd3757", size: new capnp_ts_1.ObjectSize(8, 2) };
class Constant extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getValue() { return capnp_ts_1.Struct.getInt64(0, this); }
    setValue(value) { capnp_ts_1.Struct.setInt64(0, value, this); }
    toString() { return "Constant_" + super.toString(); }
}
exports.Constant = Constant;
Constant._capnp = { displayName: "Constant", id: "e354a1a55c4cfc59", size: new capnp_ts_1.ObjectSize(8, 1) };
class Constructor extends capnp_ts_1.Struct {
    adoptArgs(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownArgs() { return capnp_ts_1.Struct.disown(this.getArgs()); }
    getArgs() { return capnp_ts_1.Struct.getList(0, Constructor._Args, this); }
    hasArgs() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initArgs(length) { return capnp_ts_1.Struct.initList(0, Constructor._Args, length, this); }
    setArgs(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Constructor_" + super.toString(); }
}
exports.Constructor = Constructor;
Constructor._capnp = { displayName: "Constructor", id: "f4610fdb47099d17", size: new capnp_ts_1.ObjectSize(0, 1) };
var Module_Which;
(function (Module_Which) {
    Module_Which[Module_Which["STRUCTURE_NAME"] = 0] = "STRUCTURE_NAME";
    Module_Which[Module_Which["TS_DECLARATIONS"] = 1] = "TS_DECLARATIONS";
})(Module_Which = exports.Module_Which || (exports.Module_Which = {}));
class Module extends capnp_ts_1.Struct {
    getSpecifier() { return capnp_ts_1.Struct.getText(0, this); }
    setSpecifier(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getStructureName() {
        capnp_ts_1.Struct.testWhich("structureName", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isStructureName() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setStructureName(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    getTsDeclarations() {
        capnp_ts_1.Struct.testWhich("tsDeclarations", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getText(1, this);
    }
    isTsDeclarations() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setTsDeclarations(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.setText(1, value, this);
    }
    toString() { return "Module_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
exports.Module = Module;
Module.STRUCTURE_NAME = Module_Which.STRUCTURE_NAME;
Module.TS_DECLARATIONS = Module_Which.TS_DECLARATIONS;
Module._capnp = { displayName: "Module", id: "cd4221e3248069bd", size: new capnp_ts_1.ObjectSize(8, 2) };
class StructureGroups_StructureGroup extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getText(0, this); }
    setName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    adoptStructures(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownStructures() { return capnp_ts_1.Struct.disown(this.getStructures()); }
    getStructures() { return capnp_ts_1.Struct.getList(1, StructureGroups_StructureGroup._Structures, this); }
    hasStructures() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initStructures(length) { return capnp_ts_1.Struct.initList(1, StructureGroups_StructureGroup._Structures, length, this); }
    setStructures(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "StructureGroups_StructureGroup_" + super.toString(); }
}
exports.StructureGroups_StructureGroup = StructureGroups_StructureGroup;
StructureGroups_StructureGroup._capnp = { displayName: "StructureGroup", id: "fe89d9d03a268a31", size: new capnp_ts_1.ObjectSize(0, 2) };
class StructureGroups extends capnp_ts_1.Struct {
    adoptGroups(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownGroups() { return capnp_ts_1.Struct.disown(this.getGroups()); }
    getGroups() { return capnp_ts_1.Struct.getList(0, StructureGroups._Groups, this); }
    hasGroups() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initGroups(length) { return capnp_ts_1.Struct.initList(0, StructureGroups._Groups, length, this); }
    setGroups(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptModules(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownModules() { return capnp_ts_1.Struct.disown(this.getModules()); }
    getModules() { return capnp_ts_1.Struct.getList(1, StructureGroups._Modules, this); }
    hasModules() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initModules(length) { return capnp_ts_1.Struct.initList(1, StructureGroups._Modules, length, this); }
    setModules(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "StructureGroups_" + super.toString(); }
}
exports.StructureGroups = StructureGroups;
StructureGroups.StructureGroup = StructureGroups_StructureGroup;
StructureGroups._capnp = { displayName: "StructureGroups", id: "ed8c71dbb06eb831", size: new capnp_ts_1.ObjectSize(0, 2) };
class JsBuiltinType extends capnp_ts_1.Struct {
    getModule() { return capnp_ts_1.Struct.getText(0, this); }
    setModule(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getExport() { return capnp_ts_1.Struct.getText(1, this); }
    setExport(value) { capnp_ts_1.Struct.setText(1, value, this); }
    toString() { return "JsBuiltinType_" + super.toString(); }
}
exports.JsBuiltinType = JsBuiltinType;
JsBuiltinType._capnp = { displayName: "JsBuiltinType", id: "ccf1cde29b10a0bb", size: new capnp_ts_1.ObjectSize(0, 2) };
OneOfType._Variants = capnp.CompositeList(Type);
FunctionType._Args = capnp.CompositeList(Type);
Structure._Members = capnp.CompositeList(Member);
Structure._BuiltinModules = capnp.CompositeList(Module);
Method._Args = capnp.CompositeList(Type);
Constructor._Args = capnp.CompositeList(Type);
StructureGroups_StructureGroup._Structures = capnp.CompositeList(Structure);
StructureGroups._Groups = capnp.CompositeList(StructureGroups_StructureGroup);
StructureGroups._Modules = capnp.CompositeList(Module);
