/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=./workflows-exports/wrangler.jsonc --include-runtime=false ./workflows-exports/src/env.d.ts` (hash: 0c8cd5ae12176ebab8337cbfef98b516)
interface __BaseEnv_Env {}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
