/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime ./src/env.d.ts` (hash: c884143a624d7ee658a821580d85d3d2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		ECHO_SERVER_HYPERDRIVE: Hyperdrive;
	}
}
interface Env extends Cloudflare.Env {}
