name: "Install Dependencies"
description: "Install dependencies, fetching from cache when possible"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: "pnpm"

    - name: ESlint and Typescript caching
      uses: actions/cache@v3
      id: eslint-cache
      with:
        path: |
          .eslintcache
          tsconfig.tsbuildinfo
        key: ${{ matrix.os }}-eslint-tsbuildinfo-${{ hashFiles('**/*.ts','**/*.js', 'package.json', 'tsconfig.json') }}

    - shell: bash
      name: Install NPM Dependencies
      run: pnpm install --frozen-lockfile
