name: "Install Dependencies"
description: "Install dependencies, fetching from cache when possible"
inputs:
  node-version:
    description: the version of Node.js to install
    default: 18.20.2
  turbo-api:
    description: the api URL for connecting to the turbo remote cache
  turbo-team:
    description: the team identifier for connecting to the turbo remote cache
  turbo-token:
    description: the api token for connecting to the turbo remote cache
  turbo-signature:
    description: the cache signature key for connecting to the turbo remote cache
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.12.0

    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"

    - name: "Configure turbo repo cache environment variables"
      if: inputs.turbo-api
      shell: bash
      run: |
        touch .env
        echo TURBO_API=${{ inputs.turbo-api }} >> .env
        echo TURBO_TEAM=${{ inputs.turbo-team }} >> .env
        echo TURBO_TOKEN=${{ inputs.turbo-token }} >> .env
        echo TURBO_REMOTE_CACHE_SIGNATURE_KEY=${{ inputs.turbo-signature }} >> .env

    - name: Install NPM Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
