name: "Install Dependencies"
description: "Install dependencies, fetching from cache when possible"
inputs:
  # We run all jobs on Node.js 22 by default, as this is the most stable and supported version right now.
  node-version:
    description: the version of Node.js to install
    default: 22
  turbo-api:
    description: the api URL for connecting to the turbo remote cache
  turbo-team:
    description: the team identifier for connecting to the turbo remote cache
  turbo-token:
    description: the api token for connecting to the turbo remote cache
  turbo-signature:
    description: the cache signature key for connecting to the turbo remote cache
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.12.0

    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"

    # Enable node compile cache (effective for Node 22+)
    # See https://nodejs.org/docs/v24.11.1/api/module.html#module-compile-cache
    - name: Enable Node Compile Cache
      shell: bash
      run: echo "NODE_COMPILE_CACHE=$HOME/.node_compile_cache" >> $GITHUB_ENV

    - name: "Configure turbo repo cache environment variables"
      if: inputs.turbo-api
      shell: bash
      run: |
        touch .env
        echo TURBO_API=${{ inputs.turbo-api }} >> .env
        echo TURBO_TEAM=${{ inputs.turbo-team }} >> .env
        echo TURBO_TOKEN=${{ inputs.turbo-token }} >> .env
        echo TURBO_REMOTE_CACHE_SIGNATURE_KEY=${{ inputs.turbo-signature }} >> .env
        echo TURBO_ENV_MODE=loose >> .env

    - name: Install NPM Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
