/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: d339939ecae5b712a3e95cce7f8d045f)
interface InternalEnv {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
