// Generated by Wrangler by running `wrangler types --no-include-runtime`

interface Env {
	KV_B: KVNamespace;
	DB_B: D1Database;
	DO_B: DurableObjectNamespace<import("./index").WorkerBDurableObject>;
}
