/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./worker-b/worker-configuration.d.ts -c ./worker-b/wrangler.jsonc --no-include-runtime` (hash: 632ffafa3dc5862cbf624297e9a5e94f)
interface __EnvShape_Env {
	KV_B: KVNamespace;
	BUCKET_B: R2Bucket;
	DB_B: D1Database;
	DO_B: DurableObjectNamespace<import("./index").WorkerBDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "WorkerBDurableObject";
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
