/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./multiple-workers/database-service/src/env.d.ts -c ./multiple-workers/database-service/wrangler.jsonc --no-include-runtime` (hash: 836c8ec92bcd45633fe61ef63340d336)
interface __BaseEnv_Env {
	KV_NAMESPACE: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
