/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fe3ebc7566ae43adebefcd6cfba26ae2)
interface InternalEnv {
	KV: KVNamespace;
	CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: string;
	HELLO_WORLD: HelloWorldBinding;
	WAE: AnalyticsEngineDataset;
	RATE_LIMITER: RateLimit;
	HYPERDRIVE: Hyperdrive;
	IMAGES: ImagesBinding;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
