/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2aff1a83eda1c659fd494a8ca649c27a)
declare namespace Cloudflare {
	interface Env {
		KV: KVNamespace;
		HELLO_WORLD: HelloWorldBinding;
	}
}
interface Env extends Cloudflare.Env {}
