/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./container-app/src/env.d.ts -c ./container-app/wrangler.jsonc --no-include-runtime` (hash: 45be8189fa807ec0c802f13cfd9b1a25)
interface __BaseEnv_Env {
	MY_CONTAINER: DurableObjectNamespace<import("./index").MyContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "MyContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
