/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=./container-app/wrangler.jsonc --include-runtime=false ./container-app/src/env.d.ts` (hash: 0f5b8dcfe752e2d3d7b74ec5c89e9b07)
interface __BaseEnv_Env {
	EXPERIMENTAL_CLOUDFLARE_CONTAINER_IMAGES: Readonly<
		Record<string, Readonly<Record<string, string>>>
	>;
	NAMED_CONTAINER: DurableObjectNamespace<
		import("./index").NamedImageContainer
	>;
	DEFAULT_CONTAINER: DurableObjectNamespace<
		import("./index").DefaultImageContainer
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "NamedImageContainer" | "DefaultImageContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
