organization: cloudflare
stickers:
  - id: cltg4w6r612040fl2r7vweuvv
    alias: outstanding contribution

holobytes:
  - evolvingStickerId: cltg4rlqc39020fl51scnguhb
    alias: contribution
    in: true
