name = "worker-a"
main = "./index.ts"
compatibility_date = "2024-09-09"

services = [
	{ binding = "WORKER_B", service = "worker-b" },
	{ binding = "NAMED_ENTRYPOINT", service = "worker-b", entrypoint = "NamedEntrypoint" },
]
