/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./multiple-workers/api-service/src/env.d.ts -c ./multiple-workers/api-service/wrangler.jsonc --no-include-runtime` (hash: 962f271af6efbacba59647ce2695a03a)
interface InternalEnv {
	AUTH_SERVICE: Fetcher /* auth-service */;
	DATABASE_SERVICE: Fetcher /* database-service */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
