/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./multiple-workers/api-service/src/env.d.ts -c ./multiple-workers/api-service/wrangler.jsonc --no-include-runtime` (hash: d30d9df78aefbaad596e0d3b5c9ea4a4)
interface __EnvShape_Env {
	AUTH_SERVICE: Fetcher /* auth-service */;
	DATABASE_SERVICE: Fetcher /* database-service */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
