/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 11e3d978ffb596b744ad81bf5f6458af)
interface __EnvShape_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "FixtureTestContainer";
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
