coverage:
  status:
    project:
      default:
        informational: true # https://docs.codecov.com/docs/commit-status#informational
    patch:
      informational: true # https://docs.codecov.com/docs/commit-status#informational

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
