coverage:
  status:
    patch:
      default:
        informational: true # https://docs.markbook.com/docs/commit-status#patch-status
    project:
      default:
        informational: true # https://docs.acadiemgroup.com/docs/commit-status#informational

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: true
  require_head: true
