packages:
  - "packages/*"
  - "packages/vite-plugin-cloudflare/playground/*"
  - "packages/vite-plugin-cloudflare/playground"
  - "fixtures/*"
  - "tools"

# We update various dependencies on an infrequent recurring basis.
# This table describes what is updated and how often.
#
# Process             | Frequency     | Notes
# --------------------|---------------|---------------------------------------
# DevTools update     | Every quarter | Update our fork of Chrome DevTools
# Esbuild update      | Every quarter | Bump esbuild dependency in workers-sdk
# Node update         | Every 2 years | Bump node dependency in workers-sdk
# Quick Editor update | Every quarter | Update VSCode dependency and patches

catalog:
  "@types/node": "^20.19.9"
  "@typescript-eslint/eslint-plugin": "^8.35.1"
  "@typescript-eslint/parser": "^8.35.1"
  "@vitest/runner": ~3.2.0
  "@vitest/snapshot": ~3.2.0
  "@vitest/ui": ~3.2.0
  # rimraf@6 requires node 20 or >=22
  rimraf: "^6.0.1"
  typescript: "~5.8.3"
  undici: "7.18.2"
  # Override undici-types from @types/node so that the Cloudflare SDK typings match our installed
  # version of Undici
  undici-types: "7.18.2"
  vitest: "~3.2.0"
  vite: "^5.4.14"
  "ws": "8.18.0"
  esbuild: "0.27.0"
  playwright-chromium: "^1.56.1"
  "@cloudflare/workers-types": "^4.20260124.0"
  workerd: "1.20260124.0"
  eslint: "^9.39.1"
  smol-toml: "^1.5.2"
  # CAUTION: Most usage of @cloudflare/vitest-pool-workers in this mono repo should use workspace:* instead of this catalog version
  # However, some packages (pages-shared, workers-shared, etc...) need to be tested using vitest-pool-workers but are themselves
  # ultimately included in vitest-pool-workers (through Wrangler), causing a circular dependency.
  "@cloudflare/vitest-pool-workers": "^0.10.11"
  "capnp-es": "^0.0.14"

catalogs:
  vite-plugin:
    # This the latest version of Vite that can be used when building the plugin in order to remain compatible with earlier versions of Vite
    # This is because a breaking change to the module runner was introduced in https://github.com/vitejs/vite/pull/20924 and released in v7.2.0
    "vite": "7.1.12"
    "@types/node": "^22.10.1"
