packages:
  - "packages/*"
  - "packages/vite-plugin-cloudflare/playground/*"
  - "packages/vite-plugin-cloudflare/playground"
  - "fixtures/*"
  - "tools"

catalog:
  "@types/node": "^18.19.71"
  "@vitest/runner": "~2.1.9"
  "@vitest/snapshot": "~2.1.9"
  "@vitest/ui": "~2.1.9"
  # rimraf@6 requires node 20 or >=22
  rimraf: "^5.0.10"
  typescript: "^5.7.2"
  undici: "^5.28.4"
  vitest: "~2.1.9"
  vite: "^5.4.14"

catalogs:
  vite-plugin:
    "vite": "^6.1.0"
    "@types/node": "^22.10.1"
    # This is the minimum Wrangler peer dependency for Vite
    "wrangler": "^3.101.0"
