packages:
  - "packages/*"
  - "fixtures/*"
  - "tools"

catalog:
  "@types/node": "^18.19.59"
  "@vitest/runner": ~2.1.8
  "@vitest/snapshot": ~2.1.8
  "@vitest/ui": ~2.1.8
  # rimraf@6 requires node 20 or >=22
  rimraf: "^5.0.10"
  typescript: "~5.6.3"
  undici: "^5.28.4"
  vitest: ~2.1.8
