packages:
  - "packages/*"
  - "packages/vite-plugin-cloudflare/playground/*"
  - "packages/vite-plugin-cloudflare/playground"
  - "fixtures/*"
  - "tools"

# We update various dependencies on an infrequent recurring basis.
# This table describes what is updated and how often.
#
# Process             | Frequency     | Notes
# --------------------|---------------|---------------------------------------
# DevTools update     | Every quarter | Update our fork of Chrome DevTools
# Esbuild update      | Every quarter | Bump esbuild dependency in workers-sdk
# Node update         | Every 2 years | Bump node dependency in workers-sdk
# Quick Editor update | Every quarter | Update VSCode dependency and patches

catalog:
  "@types/node": "^20.17.32"
  "@vitest/runner": ~3.2.0
  "@vitest/snapshot": ~3.2.0
  "@vitest/ui": ~3.2.0
  # rimraf@6 requires node 20 or >=22
  rimraf: "^6.0.1"
  typescript: "^5.7.2"
  undici: "^5.28.5"
  vitest: "~3.2.0"
  vite: "^5.4.14"
  "ws": "8.18.0"
  esbuild: "0.25.4"
  playwright-chromium: "^1.49.1"

catalogs:
  vite-plugin:
    "vite": "^6.1.0"
    "@types/node": "^22.10.1"
