packages:
  - "packages/*"
  - "packages/vite-plugin-cloudflare/playground/*"
  - "packages/vite-plugin-cloudflare/playground"
  - "fixtures/*"
  - "tools"

catalog:
  "@types/node": "^18.19.75"
  "@vitest/runner": ~3.0.5
  "@vitest/snapshot": ~3.0.5
  "@vitest/ui": ~3.0.5
  # rimraf@6 requires node 20 or >=22
  rimraf: "^6.0.1"
  typescript: "^5.7.2"
  undici: "^5.28.5"
  vitest: "~3.0.5"
  vite: "^5.4.14"
  "ws": "8.18.0"

catalogs:
  vite-plugin:
    "vite": "^6.1.0"
    "@types/node": "^22.10.1"
    # This is the minimum Wrangler peer dependency for Vite
    "wrangler": "^3.101.0"
