packages:
  - "packages/*"
  - "fixtures/*"
  - "tools"

catalog:
  "@types/node": "^18.19.75"
  "@vitest/runner": ~3.0.5
  "@vitest/snapshot": ~3.0.5
  "@vitest/ui": ~3.0.5
  # rimraf@6 requires node 20 or >=22
  rimraf: "^5.0.10"
  typescript: "^5.7.2"
  undici: "^5.28.5"
  vitest: "~3.0.5"
  vite: "^5.4.14"
  "ws": "8.18.0"
