packages:
  - "packages/*"
  - "fixtures/*"
  - "tools"

catalog:
  vitest: ~2.1.1
  "@vitest/runner": ~2.1.1
  "@vitest/snapshot": ~2.1.1
  undici: "^5.28.4"
  typescript: "~5.5.4"
  "@types/node": "^18.19.59"
