/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 91cbc55cc65371e016c4800923a8d320)
interface __EnvShape_Env {
	MY_WORKER: Fetcher /* my-staging-worker-test */ | Fetcher /* my-worker-test */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		MY_WORKER: Fetcher /* my-staging-worker-test */;
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
