/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=./workers/mock-browser/wrangler.jsonc --include-runtime=false ./workers/mock-browser/worker-configuration.d.ts` (hash: 87fea83c932800c6b528274dcf456c06)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Workers {
		"mock-browser": {
			env: __BaseEnv_Env;
			module: typeof import("./index");
		};
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
