#:schema node_modules/wrangler/config-schema.json
name = "<TBD>"
compatibility_date = "<TBD>"
compatibility_flags = ["nodejs_compat"]
main = "./dist/worker/index.js"
assets = { directory = "./dist/public", binding = "ASSETS" }

# Workers Logs
# Docs: https://rohin-observability-docs.cloudflare-docs-7ou.pages.dev/workers/observability/logs/workers-logs/
# Configuration: https://rohin-observability-docs.cloudflare-docs-7ou.pages.dev/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
