#:schema node_modules/wrangler/config-schema.json
name = "<TBD>"
compatibility_date = "<TBD>"
compatibility_flags = ["nodejs_compat"]
main = "./dist/worker/index.js"
experimental_assets = { directory = "./dist/public", binding = "ASSETS" }
