// Generated by Wrangler on Thu Aug 29 2024 19:37:30 GMT+0100 (British Summer Time)
// by running `wrangler types --x-include-runtime`

interface Env {
	DB_HOSTNAME: "hh-pgsql-public.ebi.ac.uk";
	DB_PORT: "5432";
	DB_NAME: "pfmegrnargs";
	DB_USERNAME: "reader";
	DB_PASSWORD: "NWDMCE5xdipIjRrp";
}
