// Generated by Wrangler on Tue Mar 05 2024 16:04:07 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types`

interface Env {
	DB_HOSTNAME: "hh-pgsql-public.ebi.ac.uk";
	DB_PORT: "5432";
	DB_NAME: "pfmegrnargs";
	DB_USERNAME: "reader";
	DB_PASSWORD: "NWDMCE5xdipIjRrp";
}
