/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./multi-workers-containers-app/workerB/worker-configuration.d.ts -c ./multi-workers-containers-app/workerB/wrangler.jsonc --no-include-runtime` (hash: a1dc0c87394c9ca84c31b129566cf5be)
interface __EnvShape_Env {
	CONTAINER_B: DurableObjectNamespace<import("./index").FixtureTestContainerB>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "FixtureTestContainerB";
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
