#:schema node_modules/wrangler/config-schema.json
name = "<TBD>"
main = "src/entry.py"
compatibility_flags = ["python_workers"]
compatibility_date = "<TBD>"
assets = { directory = "./public", binding = "ASSETS" }
