#:schema node_modules/wrangler/config-schema.json
name = "<TBD>"
main = "src/entry.py"
compatibility_flags = ["python_workers"]
compatibility_date = "<TBD>"
assets = { directory = "./public", binding = "ASSETS" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
