// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2017 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.widget {
  display: flex;
  background: var(--color-background);
  box-shadow: var(--drop-shadow);
  border-radius: 2px;
  overflow: auto;
  user-select: text;
  line-height: 11px;
}

/*# sourceURL=swatchPopover.css */
`);
export default styles;
