/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime ./src/env.d.ts` (hash: 8cc5578c4018b984d5ac1d0b13c36496)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
