name = "workers-websocket-durable-objects"
main = "src/index.ts"
compatibility_date = "2022-05-10"

# alarms are used to send a broadcast health check message
# useful to detect dead connections
compatibility_flags = ["durable_object_alarms"]

[durable_objects]
bindings = [
  { name = "DO_WEBSOCKET", class_name = "WebSocketDurableObject" },
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["WebSocketDurableObject"] # Array of new classes
