/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 1c566bed8d7b002a1b339b3c908cf1f0)
interface InternalEnv {
	BROWSER_KV_DEMO: KVNamespace;
	MYBROWSER: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
