/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 96667425caa8b4918f184e65a9c2290f)
interface __EnvShape_Env {
	BROWSER_KV_DEMO: KVNamespace;
	MYBROWSER: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
