/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime ./src/env.d.ts` (hash: c4b3a076cc10dce6f4d7266d3641d58e)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		IMAGES: ImagesBinding;
	}
}
interface Env extends Cloudflare.Env {}
