/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./images/src/env.d.ts -c ./images/wrangler.jsonc --no-include-runtime` (hash: 3741acaf2f214a7a0afd060927b2e972)
interface __EnvShape_Env {
	IMAGES: ImagesBinding;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
