// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
declare namespace Cloudflare {
	interface Env {
		VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
	}
}
interface Env extends Cloudflare.Env {}