/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./workers/default/worker-configuration.d.ts -c ./workers/default/wrangler.jsonc --no-include-runtime` (hash: 9dd56a3bf5cecada1bed29dfd0a5ffda)
interface InternalEnv {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
