name = "worker"
main = "./index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

services = [
	{ binding = "MY_SERVICE", service = "worker", entrypoint = "MyWorkerEntrypoint" },
]

[durable_objects]
bindings = [{ name = "MY_DO", class_name = "MyDurableObject" }]

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]