name = "<YOUR_WORKER_NAME>"
main = "./src/index.ts"

compatibility_date = "2022-06-30"

account_id = "YOUR_ACCOUNT_ID" # Replace with your Account ID.
workers_dev = true

[[r2_buckets]]
binding = 'MY_BUCKET' # can be any valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAME>'