/* eslint-disable */
// Generated by @cloudflare/config
import type { InferEnv, InferDurableNamespaces, InferMainModule, UnwrapConfig } from "@cloudflare/vite-plugin/experimental-config";
import type Config from "./cloudflare.config";

type WorkerConfig = UnwrapConfig<typeof Config>;

declare global {
	namespace Cloudflare {
		interface GlobalProps {
			mainModule: InferMainModule<WorkerConfig>;
			durableNamespaces: InferDurableNamespaces<WorkerConfig>;
		}
		interface Env extends InferEnv<WorkerConfig> {}
	}
	interface Env extends Cloudflare.Env {}
}
