/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./rpc/src/env.d.ts -c ./rpc/wrangler.jsonc --no-include-runtime` (hash: 86dc5f25d2f0268adc69f5c054dadba6)
interface __BaseEnv_Env {
	KV_NAMESPACE: KVNamespace;
	TEST_OBJECT: DurableObjectNamespace<import("./index").TestObject>;
	PROXIED_TEST_OBJECT: DurableObjectNamespace<
		import("./index").ProxiedTestObject
	>;
	TEST_NAMED_HANDLER: Service<typeof import("./index").testNamedHandler>;
	TEST_NAMED_ENTRYPOINT: Service<typeof import("./index").TestNamedEntrypoint>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "TestObject" | "ProxiedTestObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
