/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./rpc/src/env.d.ts -c ./rpc/wrangler.jsonc --no-include-runtime` (hash: a8504f758a47f0da23fa8e1935e549b5)
interface InternalEnv {
	KV_NAMESPACE: KVNamespace;
	TEST_OBJECT: DurableObjectNamespace<import("./index").TestObject>;
	TEST_NAMED_HANDLER: Service<typeof import("./index").testNamedHandler>;
	TEST_NAMED_ENTRYPOINT: Service<typeof import("./index").TestNamedEntrypoint>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "TestObject";
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
