/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./rpc/src/env.d.ts -c ./rpc/wrangler.jsonc --no-include-runtime` (hash: 57c89eec34fe01fff7991779208a4cbe)
interface __EnvShape_Env {
	KV_NAMESPACE: KVNamespace;
	TEST_OBJECT: DurableObjectNamespace<import("./index").TestObject>;
	TEST_NAMED_HANDLER: Service<typeof import("./index").testNamedHandler>;
	TEST_NAMED_ENTRYPOINT: Service<typeof import("./index").TestNamedEntrypoint>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "TestObject";
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
