/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b79e12596bb202d6680446a4c5dec5f1)
interface __EnvShape_Env {
	STREAM: StreamBinding;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
