/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3ed91a58b933bbc9dff6d6311e67d32c)
interface InternalEnv {
	STREAM: StreamBinding;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
