/* eslint-disable */
// Generated by @cloudflare/config
type __WorkerConfig = import("wrangler/experimental-config").UnwrapConfig<typeof import("./cloudflare.config").default>;
type __Env = import("wrangler/experimental-config").InferAggregatedEnv<__WorkerConfig>;

declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: import("wrangler/experimental-config").InferMainModule<__WorkerConfig>;
		durableNamespaces: import("wrangler/experimental-config").InferDurableNamespaces<__WorkerConfig>;
	}
	interface Env extends __Env {}
	/** The modes declared in your config, or `never` if there are none. */
	type Mode = import("wrangler/experimental-config").InferModeNames<__WorkerConfig>;
	/** The `Env` for one specific mode, with that mode's overrides applied. */
	type EnvFor<TMode extends Mode> = import("wrangler/experimental-config").InferEnvForMode<__WorkerConfig, TMode>;
}
interface Env extends Cloudflare.Env {}
