/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 9985955de831c8659f102de3a745d0f2)
interface __BaseEnv_Env {
	ACCOUNT_ID: "f2ba8b5dd703a7dca481f2ea46e19296";
	SENTRY_DSN: "https://0ff0cac6ca8b492d8b551626a7b9670c@sentry10.cfdata.org/978";
	workersDev: "workers-playground-users.workers.dev";
	API_TOKEN: string;
	PROMETHEUS_TOKEN: string;
	SENTRY_ACCESS_CLIENT_SECRET: string;
	SENTRY_ACCESS_CLIENT_ID: string;
	UserSession: DurableObjectNamespace<import("./src/index").UserSession>;
	WSHIM_SOCKET: any;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "UserSession";
	}
	interface TestingEnv {
		ACCOUNT_ID: "f2ba8b5dd703a7dca481f2ea46e19296";
		SENTRY_DSN: "https://0ff0cac6ca8b492d8b551626a7b9670c@sentry10.cfdata.org/978";
		workersDev: "workers-playground-users.workers.dev";
		API_TOKEN: string;
		PROMETHEUS_TOKEN: string;
		SENTRY_ACCESS_CLIENT_SECRET: string;
		SENTRY_ACCESS_CLIENT_ID: string;
		UserSession: DurableObjectNamespace<import("./src/index").UserSession>;
		WSHIM_SOCKET: any;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.template" {
	const value: string;
	export default value;
	}