import assert from "node:assert";
import * as fs from "node:fs";
import { describe, it } from "vitest";
import { runInTempDir } from "../../../src/test-helpers";
import { resolveFromLockFile } from "./share";

// -----------------------------------------------------------------------
// Yarn Berry (v2+)
// -----------------------------------------------------------------------

describe("lockfile resolution — yarn.lock (Berry v2+)", () => {
	runInTempDir();

	it("parses Berry format with __metadata", ({ expect }) => {
		fs.writeFileSync(
			"yarn.lock",
			[
				"__metadata:",
				"  version: 8",
				"  cacheKey: 10c0",
				"",
				'"lodash@npm:^4.17.21":',
				"  version: 4.17.21",
				'  resolution: "lodash@npm:4.17.21"',
				"  languageName: node",
				"  linkType: hard",
				"",
				'"express@npm:^4.18.0":',
				"  version: 4.18.2",
				'  resolution: "express@npm:4.18.2"',
				"  languageName: node",
				"  linkType: hard",
			].join("\n")
		);

		const versions = resolveFromLockFile(process.cwd());
		assert(versions);
		expect(versions.get("lodash")).toBe("4.17.21");
		expect(versions.get("express")).toBe("4.18.2");
	});

	it("handles scoped packages", ({ expect }) => {
		fs.writeFileSync(
			"yarn.lock",
			[
				"__metadata:",
				"  version: 8",
				"",
				'"@types/node@npm:^22.0.0":',
				"  version: 22.15.17",
				'  resolution: "@types/node@npm:22.15.17"',
				"  languageName: node",
				"  linkType: hard",
			].join("\n")
		);

		const versions = resolveFromLockFile(process.cwd());
		assert(versions);
		expect(versions.get("@types/node")).toBe("22.15.17");
	});

	it("skips aliases (resolution package name differs)", ({ expect }) => {
		fs.writeFileSync(
			"yarn.lock",
			[
				"__metadata:",
				"  version: 8",
				"",
				'"my-react@npm:react@^18":',
				"  version: 18.2.0",
				'  resolution: "react@npm:18.2.0"',
				"  languageName: node",
				"  linkType: hard",
				"",
				'"lodash@npm:^4.17.21":',
				"  version: 4.17.21",
				'  resolution: "lodash@npm:4.17.21"',
				"  languageName: node",
				"  linkType: hard",
			].join("\n")
		);

		const versions = resolveFromLockFile(process.cwd());
		assert(versions);
		expect(versions.has("my-react")).toBe(false);
		expect(versions.get("lodash")).toBe("4.17.21");
	});

	it("handles multiple descriptors resolving to the same package", ({
		expect,
	}) => {
		fs.writeFileSync(
			"yarn.lock",
			[
				"__metadata:",
				"  version: 8",
				"",
				'"lodash@npm:^4.17.0, lodash@npm:^4.17.21":',
				"  version: 4.17.21",
				'  resolution: "lodash@npm:4.17.21"',
				"  languageName: node",
				"  linkType: hard",
			].join("\n")
		);

		const versions = resolveFromLockFile(process.cwd());
		assert(versions);
		expect(versions.get("lodash")).toBe("4.17.21");
	});

	it("skips entries without a version field", ({ expect }) => {
		fs.writeFileSync(
			"yarn.lock",
			[
				"__metadata:",
				"  version: 8",
				"",
				'"no-version-pkg@npm:^1.0.0":',
				'  resolution: "no-version-pkg@npm:1.0.0"',
				"  languageName: node",
				"  linkType: hard",
				"",
				'"lodash@npm:^4.17.21":',
				"  version: 4.17.21",
				'  resolution: "lodash@npm:4.17.21"',
				"  languageName: node",
				"  linkType: hard",
			].join("\n")
		);

		const versions = resolveFromLockFile(process.cwd());
		assert(versions);
		expect(versions.has("no-version-pkg")).toBe(false);
		expect(versions.get("lodash")).toBe("4.17.21");
	});
});

// -----------------------------------------------------------------------
// Yarn Classic (v1)
// -----------------------------------------------------------------------

describe("lockfile resolution — yarn.lock (Classic v1)", () => {
	runInTempDir();

	it("parses classic v1 format", ({ expect }) => {
		fs.writeFileSync(
			"yarn.lock",
			[
				"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
				"# yarn lockfile v1",
				"",
				"",
				"lodash@^4.17.21:",
				'  version "4.17.21"',
				'  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#..."',
				"  integrity sha512-...",
				"",
				"express@^4.18.2:",
				'  version "4.18.2"',
				'  resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz#..."',
				"  integrity sha512-...",
			].join("\n")
		);

		const versions = resolveFromLockFile(process.cwd());
		assert(versions);
		expect(versions.get("lodash")).toBe("4.17.21");
		expect(versions.get("express")).toBe("4.18.2");
	});

	it("handles scoped packages", ({ expect }) => {
		fs.writeFileSync(
			"yarn.lock",
			[
				"# yarn lockfile v1",
				"",
				"",
				'"@types/node@^22.0.0":',
				'  version "22.15.17"',
				'  resolved "https://registry.yarnpkg.com/@types/node/-/node-22.15.17.tgz#..."',
			].join("\n")
		);

		const versions = resolveFromLockFile(process.cwd());
		assert(versions);
		expect(versions.get("@types/node")).toBe("22.15.17");
	});

	it("skips aliases with npm: protocol", ({ expect }) => {
		fs.writeFileSync(
			"yarn.lock",
			[
				"# yarn lockfile v1",
				"",
				"",
				'"my-react@npm:react@^18":',
				'  version "18.2.0"',
				'  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz#..."',
				"",
				"lodash@^4.17.21:",
				'  version "4.17.21"',
				'  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#..."',
			].join("\n")
		);

		const versions = resolveFromLockFile(process.cwd());
		assert(versions);
		expect(versions.has("my-react")).toBe(false);
		expect(versions.get("lodash")).toBe("4.17.21");
	});

	it("returns an empty map for a merge-conflict lockfile", ({ expect }) => {
		// @yarnpkg/lockfile returns type "conflict" for lockfiles with
		// unresolved git merge markers
		fs.writeFileSync(
			"yarn.lock",
			[
				"# yarn lockfile v1",
				"",
				"",
				"lodash@^4.17.21:",
				'  version "4.17.21"',
				"<<<<<<< HEAD",
				'  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abc"',
				"=======",
				'  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#def"',
				">>>>>>>",
			].join("\n")
		);

		const versions = resolveFromLockFile(process.cwd());
		assert(versions);
		expect(versions.size).toBe(0);
	});
});
