name = "format-errors"
main = "src/index.ts"
compatibility_date = "2023-03-30"
workers_dev = false
account_id = "e35fd947284363a46fd7061634477114"

rules = [{ type = "Text", globs = ["**/*.mustache"], fallthrough = false }]

routes = [
  { pattern = "format-errors.devprod.cloudflare.dev", custom_domain = true }
]

[vars]
SENTRY_DSN = "https://1ff9df95733c4e7d9c31dc13ab05d44a@sentry10.cfdata.org/891"
