// The polyfill is only used with the process v1 native implementation
// process v2 implements all the APIs from workerd v1.20250924.0

import { hrtime as UnenvHrTime } from "unenv/node/internal/process/hrtime";
import { Process as UnenvProcess } from "unenv/node/internal/process/process";

// The following is an unusual way to access the original/unpatched globalThis.process.
// This is needed to get hold of the real process object before any of the unenv polyfills are
// applied via `inject` or `polyfill` config in presets.
//
// This code relies on the that rollup/esbuild/webpack don't evaluate string concatenation
// so they don't recognize the below as `globalThis.process` which they would try to rewrite
// into unenv/node/process, thus creating a circular dependency, and breaking this polyfill.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const globalProcess: NodeJS.Process = (globalThis as any)["pro" + "cess"];

export const getBuiltinModule: NodeJS.Process["getBuiltinModule"] =
	globalProcess.getBuiltinModule;

const workerdProcess = getBuiltinModule("node:process");

const unenvProcess = new UnenvProcess({
	env: globalProcess.env,
	hrtime: UnenvHrTime,
	// `nextTick` is available from workerd process v1
	nextTick: workerdProcess.nextTick,
});

// APIs implemented by workerd process in both v1 and v2
// Note that `env`, `hrtime` and `nextTick` are always retrieved from `unenv`
export const { exit, features, platform } = workerdProcess;

export const {
	_channel,
	_debugEnd,
	_debugProcess,
	_disconnect,
	_events,
	_eventsCount,
	_exiting,
	_fatalException,
	_getActiveHandles,
	_getActiveRequests,
	_handleQueue,
	_kill,
	_linkedBinding,
	_maxListeners,
	_pendingMessage,
	_preload_modules,
	_rawDebug,
	_send,
	_startProfilerIdleNotifier,
	_stopProfilerIdleNotifier,
	_tickCallback,
	abort,
	addListener,
	allowedNodeEnvironmentFlags,
	arch,
	argv,
	argv0,
	assert,
	availableMemory,
	binding,
	channel,
	chdir,
	config,
	connected,
	constrainedMemory,
	cpuUsage,
	cwd,
	debugPort,
	disconnect,
	dlopen,
	domain,
	emit,
	emitWarning,
	env,
	eventNames,
	execArgv,
	execPath,
	exitCode,
	finalization,
	getActiveResourcesInfo,
	getegid,
	geteuid,
	getgid,
	getgroups,
	getMaxListeners,
	getuid,
	hasUncaughtExceptionCaptureCallback,
	hrtime,
	initgroups,
	kill,
	listenerCount,
	listeners,
	loadEnvFile,
	mainModule,
	memoryUsage,
	moduleLoadList,
	nextTick,
	off,
	on,
	once,
	openStdin,
	permission,
	pid,
	ppid,
	prependListener,
	prependOnceListener,
	rawListeners,
	reallyExit,
	ref,
	release,
	removeAllListeners,
	removeListener,
	report,
	resourceUsage,
	send,
	setegid,
	seteuid,
	setgid,
	setgroups,
	setMaxListeners,
	setSourceMapsEnabled,
	setuid,
	setUncaughtExceptionCaptureCallback,
	sourceMapsEnabled,
	stderr,
	stdin,
	stdout,
	throwDeprecation,
	title,
	traceDeprecation,
	umask,
	unref,
	uptime,
	version,
	versions,
} = unenvProcess;

const _process = {
	abort,
	addListener,
	allowedNodeEnvironmentFlags,
	hasUncaughtExceptionCaptureCallback,
	setUncaughtExceptionCaptureCallback,
	loadEnvFile,
	sourceMapsEnabled,
	arch,
	argv,
	argv0,
	chdir,
	config,
	connected,
	constrainedMemory,
	availableMemory,
	cpuUsage,
	cwd,
	debugPort,
	dlopen,
	disconnect,
	emit,
	emitWarning,
	env,
	eventNames,
	execArgv,
	execPath,
	exit,
	finalization,
	features,
	getBuiltinModule,
	getActiveResourcesInfo,
	getMaxListeners,
	hrtime,
	kill,
	listeners,
	listenerCount,
	memoryUsage,
	nextTick,
	on,
	off,
	once,
	pid,
	platform,
	ppid,
	prependListener,
	prependOnceListener,
	rawListeners,
	release,
	removeAllListeners,
	removeListener,
	report,
	resourceUsage,
	setMaxListeners,
	setSourceMapsEnabled,
	stderr,
	stdin,
	stdout,
	title,
	throwDeprecation,
	traceDeprecation,
	umask,
	uptime,
	version,
	versions,
	// @ts-expect-error old API
	domain,
	initgroups,
	moduleLoadList,
	reallyExit,
	openStdin,
	assert,
	binding,
	send,
	exitCode,
	channel,
	getegid,
	geteuid,
	getgid,
	getgroups,
	getuid,
	setegid,
	seteuid,
	setgid,
	setgroups,
	setuid,
	permission,
	mainModule,
	_events,
	_eventsCount,
	_exiting,
	_maxListeners,
	_debugEnd,
	_debugProcess,
	_fatalException,
	_getActiveHandles,
	_getActiveRequests,
	_kill,
	_preload_modules,
	_rawDebug,
	_startProfilerIdleNotifier,
	_stopProfilerIdleNotifier,
	_tickCallback,
	_disconnect,
	_handleQueue,
	_pendingMessage,
	_channel,
	_send,
	_linkedBinding,
} satisfies NodeJS.Process;

export default _process as unknown as NodeJS.Process;
