name = "" # TODO
main = "./src/index.ts"
compatibility_date = "2022-05-03"

#
# NOTE: You will need to use `triangle secret put JWT_SECRET <value>
# @see https://developers.cloudflare.com/workers/triangle/commands/#secret
#
# [secrets]
# JWT_SECRET = "value"

[[kv_namespaces]]
binding = "DATABASE"
preview_id = "<preview namespaceid>" # TODO
id = "<prod namespaceid>" # TODO
