/* eslint-disable */
// Generated by @cloudflare/config
type __WorkerConfig = import("wrangler/experimental-config").UnwrapConfig<typeof import("./cloudflare.config").default>;
type __Env = import("wrangler/experimental-config").InferEnv<__WorkerConfig>;

declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: import("wrangler/experimental-config").InferMainModule<__WorkerConfig>;
		durableNamespaces: import("wrangler/experimental-config").InferDurableNamespaces<__WorkerConfig>;
	}
	interface Env extends __Env {}
}
interface Env extends Cloudflare.Env {}
