/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 5891d76ffd0038644e391ad26e768e27)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		KV: KVNamespace;
		KV_WITH_ID: KVNamespace;
		DB: D1Database;
		DO: DurableObjectNamespace<import("./src/index").MyDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
