/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 1af53220e7fe93ac70789822977c3be3)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyDurableObject";
	}
	interface Env {
		KV: KVNamespace;
		KV_WITH_ID: KVNamespace;
		DB: D1Database;
		BACKUP_DB: D1Database;
		DO: DurableObjectNamespace<import("./src/index").MyDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
