/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 3cb40c60ad0368ef8b0c10b0b8657b91)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyDurableObject";
	}
	interface Env {
		KV: KVNamespace;
		KV_WITH_ID: KVNamespace;
		DB: D1Database;
		DO: DurableObjectNamespace<import("./src/index").MyDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
