name = "social-image-demo"
main = "src/index.js"
compatibility_date = "2022-07-19"

routes = [
	{ pattern = "socialcard.cdnuptime.com", custom_domain = true }
]

[vars]
CLOUDFLARE_ACCOUNT_ID = "e9bc21da719562a3e45d77de7dd042de"
CLOUDFLARE_ACCOUNT_HASH = "T24Zz2DP7HaLOEAdMToO-g"
IMAGE_ID = "f622067a-7592-4aec-4d9e-944790513c00"
