import { execSync } from "node:child_process";
import { createHash } from "node:crypto";
import { getWorkersCIBranchName } from "@cloudflare/workers-utils";
import { logger } from "../../shared/context";

const MAX_DNS_LABEL_LENGTH = 63;
const HASH_LENGTH = 4;
const ALIAS_VALIDATION_REGEX = /^[a-z](?:[a-z0-9-]*[a-z0-9])?$/i;

/**
 * Sanitizes a branch name to create a valid DNS label alias.
 * Converts to lowercase, replaces invalid chars with dashes, removes consecutive dashes.
 */
export function sanitizeBranchName(branchName: string): string {
	return branchName
		.replace(/[^a-zA-Z0-9-]/g, "-")
		.replace(/-+/g, "-")
		.replace(/^-+|-+$/g, "")
		.toLowerCase();
}

/**
 * Gets the current branch name from CI environment or git.
 */
export function getBranchName(): string | undefined {
	// Try CI environment variable first
	const ciBranchName = getWorkersCIBranchName();
	if (ciBranchName) {
		return ciBranchName;
	}

	// Fall back to git commands
	try {
		execSync(`git rev-parse --is-inside-work-tree`, { stdio: "ignore" });
		return execSync(`git rev-parse --abbrev-ref HEAD`).toString().trim();
	} catch {
		return undefined;
	}
}

/**
 * Creates a truncated alias with hash suffix when the branch name is too long.
 * Hash from original branch name to preserve uniqueness.
 */
export function createTruncatedAlias(
	branchName: string,
	sanitizedAlias: string,
	availableSpace: number
): string | undefined {
	const spaceForHash = HASH_LENGTH + 1; // +1 for hyphen separator
	const maxPrefixLength = availableSpace - spaceForHash;

	if (maxPrefixLength < 1) {
		// Not enough space even with truncation
		return undefined;
	}

	const hash = createHash("sha256")
		.update(branchName)
		.digest("hex")
		.slice(0, HASH_LENGTH);

	const truncatedPrefix = sanitizedAlias.slice(0, maxPrefixLength);
	return `${truncatedPrefix}-${hash}`;
}

/**
 * Generates a preview alias based on the current git branch.
 * Alias must be <= 63 characters, alphanumeric + dashes only, and start with a letter.
 * Returns undefined if not in a git directory or requirements cannot be met.
 */
export function generatePreviewAlias(scriptName: string): string | undefined {
	const warnAndExit = () => {
		logger.warn(
			`Preview alias generation requested, but could not be autogenerated.`
		);
		return undefined;
	};

	const branchName = getBranchName();
	if (!branchName) {
		return warnAndExit();
	}

	const sanitizedAlias = sanitizeBranchName(branchName);

	// Validate the sanitized alias meets DNS label requirements
	if (!ALIAS_VALIDATION_REGEX.test(sanitizedAlias)) {
		return warnAndExit();
	}

	const availableSpace = MAX_DNS_LABEL_LENGTH - scriptName.length - 1;

	// If the sanitized alias fits within the remaining space, return it,
	// otherwise try truncation with hash suffixed
	if (sanitizedAlias.length <= availableSpace) {
		return sanitizedAlias;
	}

	const truncatedAlias = createTruncatedAlias(
		branchName,
		sanitizedAlias,
		availableSpace
	);

	return truncatedAlias || warnAndExit();
}
