// Generated by Wrangler on Thu May 23 2024 14:11:01 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	ALERTS_WEBHOOK: string;
	GITHUB_PAT: string;
	PROD_TEAM_ONLY_WEBHOOK: string;
	PROD_WEBHOOK: string;
	PROD_WRANGLER_CONTRIBUTORS_WEBHOOK: string;
	TEST_WEBHOOK: string;
	AI: Ai;
	PRESHARED_SECRET: string;
}
declare module "*.png" {
	const value: ArrayBuffer;
	export default value;
}
