name: "Run C3 E2E Tests"
description: "Runs the C3 E2E tests on npm, pnpm, and bun"
inputs:
  packageManager:
    description: "Which package manager to run the tests with"
    required: true
  packageManagerVersion:
    description: "Which package manager version to run the tests with"
    required: true
  quarantine:
    description: "Whether to run the tests in quarantine mode"
    required: false
  experimental:
    description: "Whether to run the tests in experimental mode"
    required: false
  framework:
    description: "When specified, will only run tests for this framework"
    required: false
  accountId:
    description: "The account id of the test account"
    required: true
  apiToken:
    description: "The api token of the test account"
    required: true
  saveDiffs:
    description: "Whether to retain diffs of framework templates during run"
    required: true

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.packageManager == 'bun' }}
      name: Install Bun ${{ inputs.packageManagerVersion }}
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.packageManagerVersion }}

    # Needed because gatsby requires git
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email wrangler@cloudflare.com
        git config --global user.name 'Wrangler automated PR updater'

    - name: E2E Tests ${{inputs.experimental && '(experimental)' || ''}}
      id: run-e2e
      shell: bash
      run: pnpm run test:e2e --filter create-cloudflare
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.apiToken }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.accountId }}
        E2E_QUARANTINE: ${{ inputs.quarantine }}
        E2E_EXPERIMENTAL: ${{ inputs.experimental }}
        FRAMEWORK_CLI_TO_TEST: ${{ inputs.framework }}
        TEST_PM: ${{ inputs.packageManager }}
        TEST_PM_VERSION: ${{ inputs.packageManagerVersion }}
        SAVE_DIFFS: ${{ inputs.saveDiffs }}
        CI_OS: ${{ runner.os }}

    - name: Upload Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-logs${{inputs.experimental && '-experimental' || ''}}-${{matrix.os}}
        path: packages/create-cloudflare/.e2e-logs${{inputs.experimental && '-experimental' || ''}}

    - name: Upload Framework Diffs
      if: ${{ steps.run-e2e.outcome == 'success' && inputs.saveDiffs == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: e2e-framework-diffs${{inputs.experimental && '-experimental' || ''}}
        path: packages/create-cloudflare/.e2e-diffs${{inputs.experimental && '-experimental' || ''}}
        overwrite: true

    - name: Fail if errors detected
      shell: bash
      if: ${{ steps.run-e2e.outcome == 'failure' }}
      run: exit 1
