name: "Run C3 E2E Tests"
description: "Runs the C3 E2E tests on npm, pnpm, and bun"
inputs:
  packageManager:
    description: "Which package manager to run the tests with"
    required: true
  quarantine:
    description: "Whether to run the tests in quarantine mode"
    required: false
  framework:
    description: "When specified, will only run tests for this framework"
    required: false
  accountId:
    description: "The account id of the test account"
    required: true
  apiToken:
    description: "The api token of the test account"
    required: true

runs:
  using: "composite"
  steps:
    - id: pm
      uses: actions/github-script@7
      env:
        PM: ${{ inputs.packageManager }}
      with:
        script: |
          const [name, version] = process.env.PM.split('@')
          core.setOutput('name', name)
          core.setOutput('version', version)

    - if: ${{ steps.pm.outputs.name == 'bun' }}
      name: Install Bun ${{ steps.pm.outputs.version }}
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ steps.pm.outputs.version }}

    # Needed because gatsby requires git
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email wrangler@cloudflare.com
        git config --global user.name 'Wrangler automated PR updater'

    - name: E2E Tests
      id: run-e2e
      shell: bash
      run: pnpm run test:e2e --filter create-cloudflare
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.apiToken }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.accountId }}
        E2E_QUARANTINE: ${{ inputs.quarantine }}
        FRAMEWORK_CLI_TO_TEST: ${{ inputs.framework }}
        TEST_PM: ${{ steps.pm.outputs.name }}
        TEST_PM_VERSION: ${{ steps.pm.outputs.version }}

    - name: Upload Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-logs-${{matrix.os}}
        path: packages/create-cloudflare/.e2e-logs
