import path from "node:path";
import { build } from "esbuild";
import type { Log } from "miniflare";

/**
 * Guesses the exports of the main Worker.
 *
 * We do this by running a lightweight esbuild of the main script, and looking at the meta-file generated by esbuild.
 *
 * - This doesn't support Python Workers, but then neither does Vitest.
 * - Workers that need to be built with Vite plugins (e.g. containing virtual imports)
 *   will likely not work with esbuild and so we won't be able to find the exports.
 *
 * This function will not throw but instead log a warning and return an empty array if it cannot determine the exports.
 */
export async function guessWorkerExports(
	entryFile: string | undefined,
	log: Log
): Promise<string[]> {
	if (entryFile === undefined) {
		return [];
	}

	entryFile = path.resolve(entryFile);

	const parsedEntryPath = path.parse(entryFile);
	if (parsedEntryPath.ext == ".py") {
		// We don't support Python Workers here.
		return [];
	}

	try {
		const result = await build({
			target: "es2024",
			loader: { ".js": "jsx", ".mjs": "jsx", ".cjs": "jsx" },
			entryPoints: [entryFile],
			metafile: true,
			bundle: false,
			write: false,
			logLevel: "silent",
		});

		const entryPoints = Object.values(result.metafile.outputs).filter(
			(output) => output.entryPoint !== undefined
		);
		if (entryPoints.length === 0) {
			throw new Error(
				`Cannot find entry-point "${entryFile}" in generated bundle.`
			);
		}
		if (entryPoints.length > 1) {
			throw new Error(
				"More than one entry-point found for generated bundle.\n" +
					entryPoints.map((output) => ` - ${output.entryPoint}`).join("\n")
			);
		}

		return entryPoints[0].exports;
	} catch (e) {
		log.warn(
			`Unable to guess the exports of the Worker entry-point "${entryFile}": ${e}`
		);
		return [];
	}
}
