// Generated by Wrangler on Wed Aug 23 2023 14:27:14 GMT-0500 (Central Daylight Time)
type Env = {
	ENVIRONMENT: 'production';
	EXPIRATION_HOURS: '168' | number;
	R2_ARTIFACT_ARCHIVE: R2Bucket;
	TURBO_TOKEN: string;
};
