name: "\U0001F41B Bug Report"
description: Report an issue or possible bug
title: "\U0001F41B BUG:"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## Quick Bug Form
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible.
  - type: dropdown
    id: products
    validations:
      required: true
    attributes:
      label: Which Cloudflare product(s) does this pertain to?
      multiple: true
      options:
        - D1
        - KV
        - Pages
        - Pub/Sub
        - Queues
        - R2
        - Workers for Platforms
        - Workers/Other
        - Wrangler
  - type: input
    attributes:
      label: What version of `Wrangler` are you using?
      placeholder: 0.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: What operating system are you using?
      placeholder: Mac, Windows, Linux (or WSL)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: Steps to reproduce
    validations:
      required: true
