name: "\U0001F680 Feature Request"
description: Have a suggestion for how to improve wrangler? Let us know!
labels: ["enhancement"]
type: Feature

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a feature request! Please let us know what you're trying to do, and how Wrangler, Miniflare, Create-Cloudflare etc... can help.

  - type: textarea
    attributes:
      label: Describe the solution
      description: A clear description of what you want to happen. Add any considered drawbacks.
    validations:
      required: true
