interface GenerateTypesOptions {
	/** Path to the config file (relative to the generated `.d.ts`). */
	configPath: string;
	/**
	 * Package name used in the `import type { ... } from "<packageName>"` line
	 * for `InferEnv`/`InferDurableNamespaces`/`InferMainModule`/`UnwrapConfig`.
	 *
	 * Defaults to `"@cloudflare/config"`. Integrations that bundle
	 * `@cloudflare/config` (e.g. `@cloudflare/vite-plugin`) should pass their
	 * own re-export path here so users don't need to depend on
	 * `@cloudflare/config` directly.
	 */
	packageName?: string;
}

/**
 * Generate the content for worker-configuration.d.ts
 *
 * @example
 * ```typescript
 * import { generateTypes } from "@cloudflare/config";
 * import { writeFileSync } from "node:fs";
 *
 * const content = generateTypes({
 *   configPath: "./worker.config.ts",
 * });
 *
 * writeFileSync("worker-configuration.d.ts", content);
 * ```
 */
export function generateTypes({
	configPath,
	packageName = "@cloudflare/config",
}: GenerateTypesOptions): string {
	// Strip .ts/.js extension for import path
	const configImportPath = configPath.replace(/\.(ts|js|mts|mjs)$/, "");

	const lines = [
		"/* eslint-disable */",
		"// Generated by @cloudflare/config",
		`import type { InferEnv, InferDurableNamespaces, InferMainModule, UnwrapConfig } from "${packageName}";`,
		`import type Config from "${configImportPath}";`,
		"",
		"type WorkerConfig = UnwrapConfig<typeof Config>;",
		"",
		"declare global {",
		"\tnamespace Cloudflare {",
		"\t\tinterface GlobalProps {",
		"\t\t\tmainModule: InferMainModule<WorkerConfig>;",
		"\t\t\tdurableNamespaces: InferDurableNamespaces<WorkerConfig>;",
		"\t\t}",
		"\t\tinterface Env extends InferEnv<WorkerConfig> {}",
		"\t}",
		"\tinterface Env extends Cloudflare.Env {}",
		"}",
		"",
	];

	return lines.join("\n");
}
