import { dedent } from "ts-dedent";

interface GenerateTypesOptions {
	/** Path to the config file (relative to the generated `.d.ts`). */
	configPath: string;
	/**
	 * Package name used in the inline `import("<packageName>")` type expressions
	 * for `InferEnv`/`InferDurableNamespaces`/`InferMainModule`/`UnwrapConfig`.
	 *
	 * Defaults to `"@cloudflare/config"`. Integrations that bundle
	 * `@cloudflare/config` (e.g. `@cloudflare/vite-plugin`) should pass their
	 * own re-export path here so users don't need to depend on
	 * `@cloudflare/config` directly.
	 */
	packageName?: string;
}

/**
 * Generate the content for worker-configuration.d.ts
 *
 * @example
 * ```typescript
 * import { generateTypes } from "@cloudflare/config";
 * import { writeFileSync } from "node:fs";
 *
 * const content = generateTypes({
 *   configPath: "./cloudflare.config.ts",
 * });
 *
 * writeFileSync("worker-configuration.d.ts", content);
 * ```
 */
export function generateTypes({
	configPath,
	packageName = "@cloudflare/config",
}: GenerateTypesOptions): string {
	// Strip .ts/.js extension for import path
	const configImportPath = configPath.replace(/\.(ts|js|mts|mjs)$/, "");

	return dedent`
		/* eslint-disable */
		// Generated by @cloudflare/config
		type __WorkerConfig = import("${packageName}").UnwrapConfig<typeof import("${configImportPath}").default>;
		type __Env = import("${packageName}").InferAggregatedEnv<__WorkerConfig>;

		declare namespace Cloudflare {
			interface GlobalProps {
				mainModule: import("${packageName}").InferMainModule<__WorkerConfig>;
				durableNamespaces: import("${packageName}").InferDurableNamespaces<__WorkerConfig>;
			}
			interface Env extends __Env {}
			/** The modes declared in your config, or \`never\` if there are none. */
			type Mode = import("${packageName}").InferModeNames<__WorkerConfig>;
			/** The \`Env\` for one specific mode, with that mode's overrides applied. */
			type EnvFor<TMode extends Mode> = import("${packageName}").InferEnvForMode<__WorkerConfig, TMode>;
		}
		interface Env extends Cloudflare.Env {}

	`;
}
