interface GenerateTypesOptions {
	/** Path to the config file (relative to project root) */
	configPath: string;
}

/**
 * Generate the content for worker-configuration.d.ts
 *
 * @example
 * ```typescript
 * import { generateTypes } from "@cloudflare/config";
 * import { writeFileSync } from "node:fs";
 *
 * const content = generateTypes({
 *   configPath: "./worker.config.ts",
 * });
 *
 * writeFileSync("worker-configuration.d.ts", content);
 * ```
 */
export function generateTypes({ configPath }: GenerateTypesOptions): string {
	// Strip .ts/.js extension for import path
	const configImportPath = configPath.replace(/\.(ts|js|mts|mjs)$/, "");

	const lines = [
		"/* eslint-disable */",
		"// Generated by @cloudflare/config",
		`import type { InferEnv, InferDurableNamespaces, InferMainModule, UnwrapConfig } from "@cloudflare/config";`,
		`import type Config from "${configImportPath}";`,
		"",
		"type WorkerConfig = UnwrapConfig<typeof Config>;",
		"",
		"declare global {",
		"\tnamespace Cloudflare {",
		"\t\tinterface GlobalProps {",
		"\t\t\tmainModule: InferMainModule<WorkerConfig>;",
		"\t\t\tdurableNamespaces: InferDurableNamespaces<WorkerConfig>;",
		"\t\t}",
		"\t\tinterface Env extends InferEnv<WorkerConfig> {}",
		"\t}",
		"\tinterface Env extends Cloudflare.Env {}",
		"}",
		"",
	];

	return lines.join("\n");
}
