// Generated by Wrangler on Tue Apr 04 2023 14:59:01 GMT+0100 (British Summer Time)
interface Env {
	SENTRY_DSN: "https://1ff9df95733c4e7d9c31dc13ab05d44a@sentry10.cfdata.org/891";
	PREVIEW: "preview.devprod.cloudflare.dev";
	RAW_HTTP: "rawhttp.devprod.cloudflare.dev";
	// Secrets
	SENTRY_ACCESS_CLIENT_SECRET: string;
	SENTRY_ACCESS_CLIENT_ID: string;
}
