/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime ./src/env.d.ts` (hash: 1f2a44dfa7e34a720d7eb94c445d24fa)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		PIPELINE: import("cloudflare:pipelines").Pipeline<
			import("cloudflare:pipelines").PipelineRecord
		>;
	}
}
interface Env extends Cloudflare.Env {}
