/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./pipelines/src/env.d.ts -c ./pipelines/wrangler.jsonc --no-include-runtime` (hash: 75410e3d85500fe5c403446edfdba23c)
interface __BaseEnv_Env {
	PIPELINE: import("cloudflare:pipelines").Pipeline<
		import("cloudflare:pipelines").PipelineRecord
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
