/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./pipelines/src/env.d.ts -c ./pipelines/wrangler.jsonc --no-include-runtime` (hash: 01083f9e5f6682a811e0fbf336645b34)
interface InternalEnv {
	PIPELINE: import("cloudflare:pipelines").Pipeline<import("cloudflare:pipelines").PipelineRecord>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
