import assert from "node:assert";
import semiver from "semiver";
import shellquote from "shell-quote";
import { AutoConfigFrameworkConfigurationError } from "../errors";
import { getInstalledPackageVersion } from "./utils/packages";
import type { AutoConfigFrameworkPackageInfo, FrameworkInfo } from ".";
import type { AutoConfigContext, AutoConfigTarget } from "../context";
import type { WorkerConfigInput } from "@cloudflare/config";
import type { PackageManager } from "@cloudflare/workers-utils";

export abstract class Framework {
	readonly id: FrameworkInfo["id"];
	readonly name: FrameworkInfo["name"];
	declare readonly env?: Readonly<Record<string, string>>;
	get commandCapabilities(): FrameworkCommandCapabilities {
		return {};
	}

	#frameworkVersion: string | undefined;
	get frameworkVersion(): string {
		assert(
			this.#frameworkVersion,
			`The version for ${JSON.stringify(this.name)} is unexpectedly missing`
		);
		return this.#frameworkVersion;
	}

	constructor(frameworkInfo: Pick<FrameworkInfo, "id" | "name">) {
		this.id = frameworkInfo.id;
		this.name = frameworkInfo.name;
	}

	resolveCommand(
		name: AutoConfigCommandName,
		command: string | undefined
	): AutoConfigCommand | undefined {
		if (!command) {
			return;
		}
		const [executable, ...args] = parseCommand(command);
		assert(executable, "The resolved project command cannot be empty");

		return {
			executable,
			args,
			supportsMode: this.commandCapabilities[name]?.supportsMode ?? false,
		};
	}

	isConfigured(
		_projectPath: string,
		{
			target: _target = "cf",
		}: {
			target?: AutoConfigTarget;
		} = {}
	): boolean {
		return false;
	}

	abstract configure(
		options: ConfigurationOptions
	): Promise<ConfigurationResults> | ConfigurationResults;

	configurationDescription?: string;

	/**
	 * Validates the installed framework version against the supported range and
	 * stores it for later access via the `frameworkVersion` getter.
	 * Warns via the context logger if the version exceeds `maximumKnownMajorVersion`.
	 *
	 * @param projectPath - Path to the project root used to resolve the installed version.
	 * @param frameworkPackageInfo - Package metadata including name and version bounds.
	 * @param context - The autoconfig context providing logger and other dependencies.
	 * @throws {AssertionError} If the installed version cannot be determined.
	 * @throws {AutoConfigFrameworkConfigurationError} If the version is below `minimumVersion`.
	 */
	validateFrameworkVersion(
		projectPath: string,
		frameworkPackageInfo: AutoConfigFrameworkPackageInfo,
		context: AutoConfigContext
	) {
		const frameworkVersion = getInstalledPackageVersion(
			frameworkPackageInfo.name,
			projectPath
		);

		assert(
			frameworkVersion,
			`Unable to detect the version of the \`${frameworkPackageInfo.name}\` package`
		);

		if (semiver(frameworkVersion, frameworkPackageInfo.minimumVersion) < 0) {
			throw new AutoConfigFrameworkConfigurationError(
				`The version of ${this.name} used in the project (${JSON.stringify(
					frameworkVersion
				)}) cannot be automatically configured. Please update the ${
					this.name
				} version to at least ${JSON.stringify(
					frameworkPackageInfo.minimumVersion
				)} and try again.`,
				{ telemetryMessage: "autoconfig framework version unsupported" }
			);
		}

		if (
			semiver(frameworkVersion, frameworkPackageInfo.maximumKnownMajorVersion) >
			0
		) {
			context.logger.warn(
				`The version of ${this.name} used in the project (${JSON.stringify(
					frameworkVersion
				)}) is not officially supported, and may fail to correctly configure. Please report any issues to https://github.com/cloudflare/workers-sdk/issues`
			);
		}

		this.#frameworkVersion = frameworkVersion;
	}
}

export type ConfigurationOptions = {
	target: AutoConfigTarget;
	outputDir: string;
	projectPath: string;
	workerName: string;
	dryRun: boolean;
	packageManager: PackageManager;
	isWorkspaceRoot: boolean;
	context: AutoConfigContext;
};

export type PackageJsonScriptsOverrides = {
	preview?: string; // legacy Wrangler preview command, default is `npm run build && wrangler dev`
	deploy?: string; // legacy Wrangler deploy command, default is `npm run build && wrangler deploy`
	typegen?: string; // default is `wrangler types`
};

export type BuildConfig = {
	assetsDirectory?: string;
};

export type AutoConfigCommandName = "build" | "dev";

export type AutoConfigCommand = {
	executable: string;
	args: string[];
	supportsMode: boolean;
};

export type AutoConfigCommands = Partial<
	Record<AutoConfigCommandName, AutoConfigCommand>
>;

export type FrameworkCommandCapabilities = Partial<
	Record<AutoConfigCommandName, Pick<AutoConfigCommand, "supportsMode">>
>;

export type BuildTool = "vite" | "wrangler";

export type ConfigurationResults = {
	/** The tool that cf should delegate build and development commands to. */
	buildTool?: BuildTool;
	/** Worker configuration generated by the framework. `null` if an external tool generates it. */
	workerConfig: Partial<WorkerConfigInput> | null;
	/** Build configuration that complements the Worker configuration. */
	buildConfig?: BuildConfig;
	// Scripts to override in the package.json. Most frameworks should not need to do this, as their default detected build command will be sufficient
	packageJsonScriptsOverrides?: PackageJsonScriptsOverrides;
	// Build command to override the standard one (`npm run build` or framework's build command)
	buildCommandOverride?: string;
	// Deploy command to override the standard one (`npx wrangler deploy`)
	deployCommandOverride?: string;
	// Version command to override the standard one (`npx wrangler versions upload`)
	versionCommandOverride?: string;
};

function parseCommand(command: string): string[] {
	const entries = shellquote.parse(
		process.platform === "win32" ? command.replaceAll("\\", "\\\\") : command
	);
	const argv: string[] = [];

	for (const entry of entries) {
		if (typeof entry === "string") {
			argv.push(entry);
		} else if ("comment" in entry) {
			continue;
		} else if (entry.op === "glob") {
			argv.push(entry.pattern);
		} else {
			throw new Error(
				`Only simple commands are supported, but found the ${JSON.stringify(entry.op)} operator in ${JSON.stringify(command)}.`
			);
		}
	}

	return argv;
}
