/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 059202c799257c021e9b01439632a694)
interface __BaseEnv_Env {
	COUNTER_A: DurableObjectNamespace<import("./src/index").CounterA>;
	COUNTER_B: DurableObjectNamespace<import("./src/index").CounterB>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CounterA" | "CounterB" | "CounterC";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
