/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./dynamic-import/src/worker-configuration.d.ts -c ./dynamic-import/wrangler.jsonc --no-include-runtime` (hash: 3db8a5d08906b2ae83ef9a0539ebae04)
interface __BaseEnv_Env {
	GREETER: DurableObjectNamespace<import("./index").GreeterDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GreeterDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
