/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./dynamic-import/src/worker-configuration.d.ts -c ./dynamic-import/wrangler.jsonc --no-include-runtime` (hash: c3a27e0588724a95a3d7d1b8cd3bb93a)
interface InternalEnv {
	GREETER: DurableObjectNamespace<import("./index").GreeterDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "GreeterDO";
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
