packages:
  - 'packages/*'
  - 'playground'
  - 'playground/*'

catalog:
  '@cloudflare/workers-types': '^4.20241205.0'
  'typescript': '^5.7.2'
  'vite': '6.0.3'
  'wrangler': '3.94.0'
  '@types/node': '^22.10.1'
  'unenv': 'npm:unenv-nightly@2.0.0-20241204-140205-a5d5190'
