/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./multiple-workers/auth-service/src/env.d.ts -c ./multiple-workers/auth-service/wrangler.jsonc --no-include-runtime` (hash: 037af28206cbced6495feb9c59739c43)
interface __EnvShape_Env {
	AUTH_PUBLIC_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
