/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./multiple-workers/auth-service/src/env.d.ts -c ./multiple-workers/auth-service/wrangler.jsonc --no-include-runtime` (hash: 63493c947fea858ba0fb4a5e476432ed)
interface InternalEnv {
	AUTH_PUBLIC_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
