import dedent from "ts-dedent";
import { CLIError } from "../cli-error";

/**
 * Thrown when a `.d.ts` file already exists at the output path but was not
 * generated by Wrangler. To avoid overwriting user-authored declarations,
 * the user must rename the existing file first.
 */
export class ConflictingTypesFileError extends CLIError {
	/**
	 * @param fileName - The base name of the conflicting file
	 *   (e.g. `"worker-configuration.d.ts"`).
	 */
	constructor(fileName: string) {
		const humanMessage = `A non-Wrangler ${fileName} already exists, please rename and try again.`;

		const aiMessage = dedent`
			Error: Conflicting Types File

			A file named "${fileName}" already exists and was not generated by Wrangler. "wrangler types" wants to write to this file, but it already contains user-authored or third-party type declarations. Overwriting it could destroy custom types.

			To resolve this, either rename the existing "${fileName}" to a different name, or specify a different output path (e.g. "wrangler types my-worker-types.d.ts"). After renaming, re-run "wrangler types".

			You may want to ask the human developer whether the existing "${fileName}" should be renamed (and to what), or whether Wrangler should output to a different file.
		`;

		super(humanMessage, aiMessage, {
			telemetryMessage: "type generation validation conflicting types file",
		});
	}
}
