#:schema node_modules/wrangler/config-schema.json
name = "<TBD>"
compatibility_date = "<TBD>"
main = ".svelte-kit/cloudflare/_worker.js"
experimental_assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }
