/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=dist/workers_sdk_flue/wrangler.json --include-runtime=false` (hash: 5d0fa593bcd93ac185a07ba6a20762a2)
interface __BaseEnv_Env {
	LOADER: WorkerLoader;
	AI: Ai;
	FLUE_BEARER_TOKEN: string;
	GITHUB_TOKEN: string;
	GITHUB_WEBHOOK_SECRET: string;
	FLUE_GITHUB_ASSISTANT_AGENT: DurableObjectNamespace<import("./dist/workers_sdk_flue/index").FlueGithubAssistantAgent>;
	FLUE_WORKSPACE_SMOKE_AGENT: DurableObjectNamespace<import("./dist/workers_sdk_flue/index").FlueWorkspaceSmokeAgent>;
	FLUE_REGISTRY: DurableObjectNamespace<import("./dist/workers_sdk_flue/index").FlueRegistry>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/workers_sdk_flue/index");
		durableNamespaces: "FlueGithubAssistantAgent" | "FlueRegistry" | "FlueWorkspaceSmokeAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FLUE_BEARER_TOKEN" | "GITHUB_TOKEN" | "GITHUB_WEBHOOK_SECRET">> {}
}
