/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=dist/workers_sdk_flue/wrangler.json --include-runtime=false` (hash: d175cb421a20d5d2f9071695b9b1fccf)
interface __BaseEnv_Env {
	LOADER: WorkerLoader;
	AI: Ai;
	FLUE_WORKSPACE_SMOKE_AGENT: DurableObjectNamespace<
		import("./dist/workers_sdk_flue/index").FlueWorkspaceSmokeAgent
	>;
	FLUE_REGISTRY: DurableObjectNamespace<
		import("./dist/workers_sdk_flue/index").FlueRegistry
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/workers_sdk_flue/index");
		durableNamespaces: "FlueRegistry" | "FlueWorkspaceSmokeAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
