/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./workers/sentry/worker-configuration.d.ts -c ./workers/sentry/wrangler.jsonc --no-include-runtime` (hash: 3cc30e2bc5fb9a21eef7eb29c5be454a)
interface __EnvShape_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
