version: '2.1'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    container_name: postgres_postgresql_1
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    environment:
      - POSTGRESQL_HOST=postgresql
      - PGBOUNCER_AUTH_TYPE=trust
    depends_on:
      - postgresql
  cloudflared:
    image: cloudflare/cloudflared:2021.10.5
    environment:
      - TUNNEL_HOSTNAME=${TUNNEL_HOSTNAME}
    volumes:
      - '~/.cloudflared:/etc/cloudflared'
    command: tunnel --url tcp://pgbouncer:6432 --name dev -f
    depends_on:
      - pgbouncer
volumes:
  postgresql_data:
    driver: local
