const HEADER_NAME_PATTERN = /^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/u;

const MANAGED_HEADER_NAMES = new Set([
	"bcc",
	"cc",
	"content-transfer-encoding",
	"content-type",
	"date",
	"from",
	"message-id",
	"mime-version",
	"reply-to",
	"subject",
	"to",
]);

/**
 * Checks whether a value is a valid email header field name.
 *
 * @param value - Header name to check.
 * @returns Whether the name contains only RFC token characters.
 */
export function isEmailHeaderName(value: string): boolean {
	return HEADER_NAME_PATTERN.test(value);
}

/**
 * Checks whether a header is generated by the test-email composer.
 *
 * @param value - Header name to check.
 * @returns Whether the composer owns the header value.
 */
export function isManagedEmailHeaderName(value: string): boolean {
	return MANAGED_HEADER_NAMES.has(value.toLowerCase());
}

/**
 * Checks for control characters that cannot safely appear in a custom header.
 * LF and CRLF are accepted because Miniflare folds them into MIME continuation
 * lines before delivery.
 *
 * @param value - Header value to check.
 * @returns Whether the value contains an unsafe control character.
 */
export function hasInvalidEmailHeaderValueCharacters(value: string): boolean {
	for (let index = 0; index < value.length; index++) {
		const codePoint = value.charCodeAt(index);
		if (codePoint === 10) {
			continue;
		}
		if (codePoint === 13 && value.charCodeAt(index + 1) === 10) {
			index += 1;
			continue;
		}
		if (codePoint < 32 || codePoint === 127) {
			return true;
		}
	}
	return false;
}
