/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=./wrangler.exports.jsonc --include-runtime=false` (hash: 29c40548d58fed974d2127c5686098ad)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/exports");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
