/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime ./src/env.d.ts` (hash: de35a57d6bc7177ec94c637baa44920c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Counter" | "SQLiteDurableObject";
	}
	interface Env {
		COUNTER: DurableObjectNamespace<import("./index").Counter>;
		SQL: DurableObjectNamespace<import("./index").SQLiteDurableObject>;
	}
}
interface Env extends Cloudflare.Env {}
