/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./durable-objects/src/env.d.ts -c ./durable-objects/wrangler.jsonc --no-include-runtime` (hash: af16b9b1024a184728af264b13b08bf9)
interface InternalEnv {
	COUNTER: DurableObjectNamespace<import("./index").Counter>;
	SQL: DurableObjectNamespace<import("./index").SQLiteDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Counter" | "SQLiteDurableObject";
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
