/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./durable-objects/src/env.d.ts -c ./durable-objects/wrangler.jsonc --no-include-runtime` (hash: 1852411471e6c39634cfdb968e5d5695)
interface __EnvShape_Env {
	COUNTER: DurableObjectNamespace<import("./index").Counter>;
	SQL: DurableObjectNamespace<import("./index").SQLiteDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Counter" | "SQLiteDurableObject";
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
