/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=dist/workers_sdk_auto_triage/wrangler.json --include-runtime=false` (hash: 27a3877ec63257cedea77b22e0ff9b64)
interface __BaseEnv_Env {
	AI: Ai;
	GITHUB_TOKEN: string;
	GITHUB_WEBHOOK_SECRET: string;
	SANDBOX: DurableObjectNamespace<import("./dist/workers_sdk_auto_triage/index").Sandbox>;
	FLUE_ISSUE_TRIAGE_AGENT: DurableObjectNamespace<import("./dist/workers_sdk_auto_triage/index").FlueIssueTriageAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/workers_sdk_auto_triage/index");
		durableNamespaces: "FlueIssueTriageAgent" | "Sandbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_TOKEN" | "GITHUB_WEBHOOK_SECRET">> {}
}
