/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: b8c135fdde28252382590bb97c7af577)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyDurableObject";
	}
	interface Env {
	}
}
interface Env extends Cloudflare.Env {}
