/* eslint-disable */
// Generated by @cloudflare/config
type __WorkerConfig = import("@cloudflare/vite-plugin/experimental-config").UnwrapConfig<typeof import("./cloudflare.config").default>;
type __Env = import("@cloudflare/vite-plugin/experimental-config").InferEnv<__WorkerConfig>;

declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: import("@cloudflare/vite-plugin/experimental-config").InferMainModule<__WorkerConfig>;
		durableNamespaces: import("@cloudflare/vite-plugin/experimental-config").InferDurableNamespaces<__WorkerConfig>;
	}
	interface Env extends __Env {}
}
interface Env extends Cloudflare.Env {}
