/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 52d05a3e7a4c54c5e95833c59e5939b8)
interface InternalEnv {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "MyDurableObject";
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
