/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./kv-r2-caches/src/env.d.ts -c ./kv-r2-caches/wrangler.jsonc --no-include-runtime` (hash: 22b885a7cf0d8ac4310bfa46471b48f4)
interface InternalEnv {
	KV_NAMESPACE: KVNamespace;
	R2_BUCKET: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
