/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./kv-r2-caches/src/env.d.ts -c ./kv-r2-caches/wrangler.jsonc --no-include-runtime` (hash: 2c94892b636e6a0220819a1397311336)
interface __EnvShape_Env {
	KV_NAMESPACE: KVNamespace;
	R2_BUCKET: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
