name = "worker"
main = "./src/index.ts"
compatibility_date = "2024-12-30"

[durable_objects]
bindings = [{ name = "COUNTERS", class_name = "Counter" }]

[[migrations]]
tag = "v1"
new_classes = ["Counter"]
