#:schema node_modules/wrangler/config-schema.json
name = "<TBD>"
compatibility_date = "<TBD>"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js"
assets = { directory = "./dist", binding = "ASSET" }
