/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./multiple-workers/api-service/src/env.d.ts -c ./multiple-workers/api-service/wrangler.jsonc --no-include-runtime` (hash: b9086500665f32aa0533c30a22adce89)
interface __BaseEnv_Env {
	AUTH_SERVICE: Fetcher /* auth-service */;
	DATABASE_SERVICE: Fetcher /* database-service */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
