compatibility_date = "2022-07-21"
main = "src/index.ts"
name = "worker-durable"

[durable_objects]
bindings = [
  {name = "Learning_DurableObjects", class_name = "DurableObject"},
]

[[migrations]]
new_classes = ["DurableObject"] 
tag = "v1" # Should be unique for each entry
