// Generated by Wrangler on Fri Aug 30 2024 17:35:30 GMT+0100 (British Summer Time)
// by running `wrangler types --x-include-runtime`

interface Env {
	SOME_BINDING: KVNamespace;
	BINDING: KVNamespace;
	HELLO: "WORLD";
	HELLO2: "WORLD";
	HELLO3: "WORLD";
	HELLO4: "WORLD";
	HELLO5: "WORLD";
}
