/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./multi-containers-app/src/worker-configuration.d.ts -c ./multi-containers-app/wrangler.jsonc --no-include-runtime` (hash: 8c63ed167747f51ecf91c0250303317f)
interface InternalEnv {
	CONTAINER_A: DurableObjectNamespace<import("./index").FixtureTestContainerA>;
	CONTAINER_B: DurableObjectNamespace<import("./index").FixtureTestContainerB>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "FixtureTestContainerA" | "FixtureTestContainerB";
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
