/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./request-mocking/src/env.d.ts -c ./request-mocking/wrangler.jsonc --no-include-runtime` (hash: ebd3d8807c5bb3014e5e0010e522c859)
interface InternalEnv {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
