/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./workflows/src/env.d.ts -c ./workflows/wrangler.jsonc --no-include-runtime` (hash: 84529125ee80eb4b92700c4efdce1e33)
interface __BaseEnv_Env {
	MODERATOR: Workflow<
		Parameters<import("./index").ModeratorWorkflow["run"]>[0]["payload"]
	>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
