#:schema node_modules/wrangler/config-schema.json
name = "<TBD>"
compatibility_date = "<TBD>"
main = "./dist/server/server.mjs"
experimental_assets = { directory = "./dist/browser", binding = "ASSETS" }
