export const INVALID_CONSUMER_SETTINGS_ERROR = 100127;
export const INVALID_QUEUE_SETTINGS_ERROR = 100128;

export const MIN_DELIVERY_DELAY_SECS = 0;
export const MAX_DELIVERY_DELAY_SECS = 86400;

export const MIN_MESSAGE_RETENTION_PERIOD_SECS = 60;
export const MAX_MESSAGE_RETENTION_PERIOD_SECS = 1209600;
