name = "images-download-counter"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-17"

[build.upload]
dir = "src"
format = "modules"
main = "./downloadCounter.mjs"

[durable_objects]
bindings = [
  { name = "DOWNLOAD_COUNTER", class_name = "DownloadCounter" }
]

[[migrations]]
tag = "v1"
new_classes = ["DownloadCounter"]