/**
 * @cloudflare/pages-functions
 *
 * Compile a Pages functions directory into a deployable worker entrypoint.
 */

import * as path from "node:path";
import { generateWorkerEntrypoint } from "./codegen.js";
import { generateConfigFromFileTree } from "./filepath-routing.js";
import { convertRoutesToRoutesJSONSpec } from "./routes-transformation.js";
import type { CompileOptions, CompileResult, UrlPath } from "./types.js";

// Re-export types
export type {
	CompileOptions,
	CompileResult,
	HTTPMethod,
	RouteConfig,
	RoutesJSONSpec,
	UrlPath,
} from "./types.js";

// Re-export utilities that may be useful
export { generateConfigFromFileTree } from "./filepath-routing.js";
export { convertRoutesToRoutesJSONSpec } from "./routes-transformation.js";
export { generateWorkerEntrypoint } from "./codegen.js";

/** Default functions directory relative to project root */
export const DEFAULT_FUNCTIONS_DIR = "functions";

/**
 * Error thrown when no routes are found in the functions directory.
 */
export class FunctionsNoRoutesError extends Error {
	constructor(message: string) {
		super(message);
		this.name = "FunctionsNoRoutesError";
	}
}

/**
 * Compile a Pages project's functions directory into a worker entrypoint.
 *
 * @param projectDirectory Path to the project root (containing the functions directory)
 * @param options Compilation options
 * @returns Compilation result containing generated code and route info
 *
 * @example
 * ```ts
 * import { compileFunctions } from '@cloudflare/pages-functions';
 *
 * const result = await compileFunctions('.', {
 *   fallbackService: 'ASSETS',
 * });
 *
 * // Write the generated entrypoint
 * await fs.writeFile('dist/worker.js', result.code);
 *
 * // Write _routes.json for Pages deployment
 * await fs.writeFile('_routes.json', JSON.stringify(result.routesJson, null, 2));
 * ```
 */
export async function compileFunctions(
	projectDirectory: string,
	options: CompileOptions = {}
): Promise<CompileResult> {
	const { baseURL = "/" as UrlPath, fallbackService = "ASSETS" } = options;

	const functionsDirectory = path.join(projectDirectory, DEFAULT_FUNCTIONS_DIR);

	// Generate route configuration from the file tree
	const config = await generateConfigFromFileTree({
		baseDir: functionsDirectory,
		baseURL: baseURL as UrlPath,
	});

	if (!config.routes || config.routes.length === 0) {
		throw new FunctionsNoRoutesError(
			`Failed to find any routes while compiling Functions in: ${functionsDirectory}`
		);
	}

	// Generate the worker entrypoint code
	const code = generateWorkerEntrypoint(config.routes, {
		functionsDirectory,
		fallbackService,
	});

	// Generate _routes.json for Pages deployment
	const routesJson = convertRoutesToRoutesJSONSpec(
		config.routes,
		"Generated by @cloudflare/pages-functions"
	);

	return {
		code,
		routes: config.routes,
		routesJson,
	};
}
