import type { Command } from "./types";

export const temporaryArgDefinition = {
	describe:
		"Create a temporary preview account when a command needs authentication in non-interactive mode",
	type: "boolean",
	default: false,
	hidden: true,
} as const;

// Commands the temporary preview-account deploy token can serve, mirroring
// DEPLOY_TOKEN_PERMISSION_GROUP_IDS in the anonymous-account-deploys worker
// (Workers, KV, D1, Hyperdrive, Queues, SSL/Certs). Pages/R2/AI/etc. aren't
// covered by the token and are intentionally excluded.
export const COMMANDS_SUPPORTING_TEMPORARY = new Set<Command>([
	// Workers (Scripts/Routes/Tail)
	"wrangler deploy",
	"wrangler delete",
	"wrangler tail",
	"wrangler triggers deploy",
	"wrangler deployments list",
	"wrangler deployments status",
	"wrangler deployments view",
	"wrangler rollback",
	"wrangler versions view",
	"wrangler versions list",
	"wrangler versions upload",
	"wrangler versions deploy",
	"wrangler versions secret put",
	"wrangler versions secret bulk",
	"wrangler versions secret delete",
	"wrangler versions secret list",
	"wrangler secret put",
	"wrangler secret delete",
	"wrangler secret list",
	"wrangler secret bulk",
	// KV
	"wrangler kv namespace create",
	"wrangler kv namespace list",
	"wrangler kv namespace delete",
	"wrangler kv namespace rename",
	"wrangler kv key put",
	"wrangler kv key list",
	"wrangler kv key get",
	"wrangler kv key delete",
	"wrangler kv bulk get",
	"wrangler kv bulk put",
	"wrangler kv bulk delete",
	// D1
	"wrangler d1 create",
	"wrangler d1 info",
	"wrangler d1 list",
	"wrangler d1 delete",
	"wrangler d1 execute",
	"wrangler d1 export",
	"wrangler d1 insights",
	"wrangler d1 time-travel info",
	"wrangler d1 time-travel restore",
	"wrangler d1 migrations create",
	"wrangler d1 migrations list",
	"wrangler d1 migrations apply",
	// Hyperdrive
	"wrangler hyperdrive create",
	"wrangler hyperdrive delete",
	"wrangler hyperdrive get",
	"wrangler hyperdrive list",
	"wrangler hyperdrive update",
	// Queues
	"wrangler queues list",
	"wrangler queues create",
	"wrangler queues update",
	"wrangler queues delete",
	"wrangler queues info",
	"wrangler queues pause-delivery",
	"wrangler queues resume-delivery",
	"wrangler queues purge",
	"wrangler queues subscription create",
	"wrangler queues subscription list",
	"wrangler queues subscription get",
	"wrangler queues subscription delete",
	"wrangler queues subscription update",
	"wrangler queues consumer add",
	"wrangler queues consumer remove",
	"wrangler queues consumer list",
	"wrangler queues consumer http add",
	"wrangler queues consumer http remove",
	"wrangler queues consumer http list",
	"wrangler queues consumer worker add",
	"wrangler queues consumer worker remove",
	"wrangler queues consumer worker list",
	// SSL/Certs
	"wrangler cert upload mtls-certificate",
	"wrangler cert upload certificate-authority",
	"wrangler cert list",
	"wrangler cert delete",
]);
