/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime ./src/env.d.ts` (hash: 59ee4c56d833f37b4bc751d34197c037)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		VECTORIZE: VectorizeIndex;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
