/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/env.d.ts --no-include-runtime` (hash: 9c7488be1476a99e68fd0102948ecb8e)
interface BaseEnv {
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends BaseEnv {}
}
interface Env extends BaseEnv {}
