/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./ai-vectorize/src/env.d.ts -c ./ai-vectorize/wrangler.jsonc --no-include-runtime` (hash: 54950e4bb5477ca70c1306130c0748c4)
interface __BaseEnv_Env {
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
