import { version as wranglerVersion } from "../../package.json";

// Re-export from @cloudflare/pages-functions — this file is kept for
// backward compatibility with existing Wrangler-internal imports and to keep
// the initial migration minimal without changing lots and lots of files
// TODO(dario): after the initial pages-functions migration remove these re-exports
export {
	MAX_FUNCTIONS_ROUTES_RULES,
	MAX_FUNCTIONS_ROUTES_RULE_LENGTH,
	ROUTES_SPEC_VERSION,
} from "@cloudflare/pages-functions";

const isWindows = process.platform === "win32";

export const MAX_ASSET_COUNT_DEFAULT = 20_000;
export const MAX_ASSET_SIZE = 25 * 1024 * 1024;
export const PAGES_CONFIG_CACHE_FILENAME = "pages.json";
export const MAX_BUCKET_SIZE = 40 * 1024 * 1024;
// Reduce the maximum number of files in a bucket on Windows
// This helps to avoid EMFILE errors when reading them into memory.
export const MAX_BUCKET_FILE_COUNT = isWindows ? 1000 : 2000;
export const BULK_UPLOAD_CONCURRENCY = 3;
export const MAX_UPLOAD_ATTEMPTS = 5;
export const MAX_UPLOAD_GATEWAY_ERRORS = 5;
export const MAX_DEPLOYMENT_ATTEMPTS = 3;
export const MAX_DEPLOYMENT_STATUS_ATTEMPTS = 5;
export const MAX_CHECK_MISSING_ATTEMPTS = 5;
export const SECONDS_TO_WAIT_FOR_PROXY = 5;
export const ROUTES_SPEC_DESCRIPTION = `Generated by wrangler@${wranglerVersion}`;
