/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./workflows/src/env.d.ts -c ./workflows/wrangler.jsonc --no-include-runtime` (hash: 14989d3cdf53d4012fb8e884cd75b4aa)
interface InternalEnv {
	MODERATOR: Workflow<Parameters<import("./index").ModeratorWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
