// Generated by Wrangler on Wed Aug 28 2024 11:00:50 GMT+0200 (Central European Summer Time)
// by running `wrangler types --x-include-runtime`

interface Env {
	METADATA: { id: string; tag: string };
}
