// Generated by Wrangler on Mon Jul 22 2024 10:41:44 GMT+0200 (Central European Summer Time)
// by running `wrangler types --x-with-runtime`

interface Env {
	METADATA: { id: string; tag: string };
}
