/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./hyperdrive/src/env.d.ts -c ./hyperdrive/wrangler.jsonc --no-include-runtime` (hash: b649c979f0061521ef2170b65cdd0101)
interface __BaseEnv_Env {
	ECHO_SERVER_HYPERDRIVE: Hyperdrive;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
