/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=./workers/web/wrangler.jsonc --config=./workers/api/wrangler.jsonc --include-runtime=false --env-interface=WebEnv ./workers/web/worker-configuration.d.ts` (hash: ba220acc5e7d9da5ae68234db2179e34)
interface __BaseEnv_WebEnv {
	BROWSER: BrowserRun;
	API: Service<typeof import("../api/index").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WebEnv {}
}
interface WebEnv extends __BaseEnv_WebEnv {}
