/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./d1/src/env.d.ts -c ./d1/wrangler.jsonc --no-include-runtime` (hash: db529685c9defc6baa1cc744b765c359)
interface __BaseEnv_Env {
	DATABASE?: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		DATABASE: D1Database;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
