// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default {
  cssContent: `/*
 * Copyright (c) 2015 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.empty-bold-text {
  display: block;
  font-size: 1.5em;
  margin: 0.83em 0;
  font-weight: bold;
}

.empty-view {
  color: var(--color-text-secondary);
  padding: 30px;
  text-align: center;
  min-width: 70px;
}

.empty-view-scroller {
  justify-content: center;
  overflow: auto;
}

.empty-view p {
  white-space: initial;
  line-height: 18px;
  max-width: 300px;
  flex-shrink: 0;
}
`
};
