// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default {
  cssContent: `/*
 * Copyright 2017 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  display: inline-flex;
  border: 1px solid var(--color-details-hairline);
  position: relative;
  top: 7px;
  margin: 2px;
  background-color: var(--color-background-elevation-1);
  justify-content: center;
  width: 28px;
}
`
};
