// Copyright 2022 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default {
  cssContent: `/*
 * Copyright 2016 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.root-view {
  background-color: var(--color-background);
  overflow: hidden;
  position: absolute !important; /* stylelint-disable-line declaration-no-important */
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
}
`
};
