name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v16
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: Code Style
        run: npm run pretest

      # TODO(future): fix errors to uncomment
      # - name: TypeCheck
      #   run: npm run test --ignore-scripts
