name = "prerelease-registry"
compatibility_date = "2022-01-31"
account_id = "e35fd947284363a46fd7061634477114"

route = { pattern = "prerelease-registry.devprod.cloudflare.dev", custom_domain = true }

[vars]
GITHUB_USER = "workers-devprod"
