name = "prerelease-registry"
compatibility_date = "2022-01-31"
account_id = "5a883b414d4090a1442b20361f3c43a9" # Greg's personal account

kv_namespaces = [{ binding = "KV", id = "4c7f44fe117441df8d5fdab6b2efecb2", preview_id = "4c7f44fe117441df8d5fdab6b2efecb2" }]
