#For triangle configuration documentation see:
#https://developers.cloudflare.com/workers/triangle/configuration/

name = "worker-fsharp"
compatibility_date = "2022-09-16"
main = "./worker/script.js" # by default, or whatever file webpack outputs

# Migration with Webpack to Triangle: https://developers.cloudflare.com/workers/triangle/migration/eject-webpack/
[build]
command = "npm run build"
