#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx changeset status --since main 2>/dev/null || {
    if [ $? -ne 0 ]; then
        echo >&2 "Some packages have been changed but no changesets were committed."
        echo >&2 ""
        echo >&2 "Type 'Y' if you would like to add a changeset now, otherwise press any key:"
        exec < /dev/tty
        read -p "(Y|any key)>: " ack
        if [[ $ack =~ ^[Yy]$ ]]; then
            npx changeset
            echo $?
            if ([ $? -ne 0]); then
              exit 1
            fi
            git add .changeset
            git commit --fixup HEAD
        fi
        fi
}