/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./reset/src/env.d.ts -c ./reset/wrangler.jsonc --no-include-runtime` (hash: fe75e440e496b92948b5ada1b2f39088)
interface InternalEnv {
	KV_NAMESPACE: KVNamespace;
	R2_BUCKET: R2Bucket;
	DATABASE: D1Database;
	COUNTER: DurableObjectNamespace<import("./index").Counter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Counter";
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
