/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./reset/src/env.d.ts -c ./reset/wrangler.jsonc --no-include-runtime` (hash: 0995b4ee37099bbdf3a4e6170a40f83c)
interface __EnvShape_Env {
	KV_NAMESPACE: KVNamespace;
	R2_BUCKET: R2Bucket;
	DATABASE: D1Database;
	COUNTER: DurableObjectNamespace<import("./index").Counter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Counter";
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
