/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./reset/src/env.d.ts -c ./reset/wrangler.jsonc --no-include-runtime` (hash: 524c60174bc1732153e84c1b8699023e)
interface __BaseEnv_Env {
	KV_NAMESPACE: KVNamespace;
	R2_BUCKET: R2Bucket;
	DATABASE: D1Database;
	COUNTER: DurableObjectNamespace<import("./index").Counter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Counter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
