name = "<TBD>"
main = "src/index.ts"
compatibility_date = "<TBD>"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/queues/get-started
[[queues.producers]]
binding = "MY_QUEUE"
queue = "my-queue"

# Bind a Queue consumer. Queue Consumers can retrieve tasks scheduled by Producers to act on them.
# Docs: https://developers.cloudflare.com/queues/get-started
[[queues.consumers]]
queue = "my-queue"
# Optional: Configure batching and retries: https://developers.cloudflare.com/queues/learning/batching-retries/
# max_batch_size = 10
# max_batch_timeout = 30
# max_retries = 10
# dead_letter_queue = "my-queue-dlq"
