/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./multi-workers-containers-app/workerA/worker-configuration.d.ts -c ./multi-workers-containers-app/workerA/wrangler.jsonc --no-include-runtime` (hash: 4da712048dc830f206c9baddee736fa8)
interface __EnvShape_Env {
	CONTAINER_A: DurableObjectNamespace<import("./index").FixtureTestContainerA>;
	WORKER_B: Fetcher /* worker-b */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "FixtureTestContainerA";
	}
	interface Env extends __EnvShape_Env {}
}
interface Env extends __EnvShape_Env {}
