name: C3 Checks

on:
  pull_request:
    paths:
      - packages/create-cloudflare/**

env:
  node-version: 18.17.1

jobs:
  check:
    name: "Checks"
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check Types
        run: pnpm run --filter create-cloudflare check:type

      - name: Lint
        run: pnpm run --filter create-cloudflare check:lint

      - name: Unit Tests
        run: pnpm run --filter create-cloudflare test:unit
