# This workflow cleans up any leftover projects created by e2e runs.

name: C3 E2E Project Cleanup
on:
  schedule:
    - cron: "0 3 * * *" # Run at 3am each day
env:
  node-version: 18.17.1
jobs:
  cleanup:
    timeout-minutes: 30
    name: "Cleanup Test Projects"
    if: ${{ github.repository_owner == 'cloudflare' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Cleanup E2E test projects
        run: pnpm run --filter create-cloudflare test:e2e:cleanup
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.C3_TEST_CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.C3_TEST_CLOUDFLARE_ACCOUNT_ID }}
