name: Create Changeset PR

on:
  push: 
    branches:
      - main
      
jobs:
  changeset-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.7
        uses: actions/setup-node@v2
        with:
          node-version: 16.7

      - name: Install Dependencies
        run: npm install

      - name: Create PR
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}