name: Publish Devtools

on:
  push:

jobs:
  publish:
    if: ${{ github.repository_owner == 'cloudflare' }}
    name: Build & Publish a branch preview of devtools to Cloudflare
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm" # cache ~/.npm in case 'npm ci' needs to run

      - name: Run Devtools release & publish
        run: cd packages/wrangler-devtools && make publish
        env:
          CLOUDFLARE_ACCOUNT_ID: "e35fd947284363a46fd7061634477114"
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
