name: Publish Devtools

on:
  push:
    branches:
      - main
      - "devtools/**"
      - "**-devtools"

jobs:
  publish:
    if: ${{ github.repository_owner == 'cloudflare' }}
    name: Build & Publish a branch preview of devtools to Cloudflare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"

      - name: Install workerd Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y libc++1

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Run Devtools release & publish
        run: cd packages/wrangler-devtools && make publish
        env:
          CLOUDFLARE_ACCOUNT_ID: "e35fd947284363a46fd7061634477114"
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
