name: Error Formatting Worker

on:
  push:
    branches:
      - main
jobs:
  publish_worker:
    if: ${{ github.repository_owner == 'cloudflare' }}
    name: Publish Worker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.8.0
      - name: Use Node.js 16.14
        uses: actions/setup-node@v3
        with:
          node-version: 16.14
          cache: "pnpm"

      - name: Install workerd Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install -y libc++1
      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build wrangler
        run: pnpm run build
        env:
          NODE_ENV: "production"

      - name: Build & Publish Worker
        run: pnpm run publish
        env:
          NODE_ENV: "production"
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        working-directory: packages/format-errors
