addEventListener("fetch", event => {
    event.respondWith(handleRequest(event.request));
});

async function handleRequest(request) {
    let url = new URL(request.url);
    url.hostname = "mburley.dreamvacations.com"; // Target domain

    let newRequest = new Request(url.toString(), {
        method: request.method,
        headers: request.headers,
        body: request.body,
        redirect: 'follow'
    });

    let response = await fetch(newRequest);
    return response;
}
