name: Pages

on:
  push:
    branches:
      - pages

jobs:
  build:
    name: Build & Publish an alpha release to NPM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.7]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Dependencies
        run: npm install

      - name: Copy README.md
        run: cp README.md packages/wrangler/README.md

      - name: Modify package.json version
        run: node .github/version-script.js

      - name: Build
        run: npm run build
        working-directory: packages/wrangler

      - name: Publish Alpha to NPM
        run: npm publish --tag pages
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        working-directory: packages/wrangler
