name: Deploy all Pages sites

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  filter-packages:
    strategy:
      matrix:
        package: ["workers-playground", "other-playground"]
    name: Build & Deploy Playground Shell to Cloudflare Pages
    runs-on: ubuntu-latest

    steps:
      - id: preview-label
        run: echo "label=${{ matrix.package }}-preview" >> "$GITHUB_OUTPUT"

      - id: is-match
        run: echo "continue=${{ github.repository_owner == 'cloudflare' && (github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.*.labels.*.name, steps.preview-label.outputs.label )) )}}" >> "$GITHUB_OUTPUT"

      - name: Checkout Repo
        if: steps.is-match.outputs.continue == 'true'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        if: steps.is-match.outputs.continue == 'true'
        uses: ./.github/actions/install-dependencies

      - name: Build
        if: steps.is-match.outputs.continue == 'true'
        run: pnpm run build

      - name: Deploy Playground Shell to Pages
        run: pnpm --filter ${{ matrix.package }} run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: "e35fd947284363a46fd7061634477114"
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
