name: Prerelease

on:
  pull_request:
  push:
    branches:
      - main
      - d1
      - workflows
      - next
      - v3-maintenance

jobs:
  build:
    if: ${{ github.repository_owner == 'cloudflare' }}
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          turbo-api: ${{ secrets.TURBO_API }}
          turbo-team: ${{ secrets.TURBO_TEAM }}
          turbo-token: ${{ secrets.TURBO_TOKEN }}
          turbo-signature: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
          node-version: 22

      - run: echo ${{ github.head_ref }}

      - name: Build
        run: pnpm run build
        env:
          NODE_ENV: "production"
          CI_OS: ${{ runner.os }}
          # this is the "test/staging" key for sparrow analytics
          SPARROW_SOURCE_KEY: "5adf183f94b3436ba78d67f506965998"
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          SENTRY_DSN: "https://9edbb8417b284aa2bbead9b4c318918b@sentry10.cfdata.org/583"
          ALGOLIA_PUBLIC_KEY: ${{ secrets.ALGOLIA_PUBLIC_KEY }}
          WRANGLER_PRERELEASE_LABEL: ${{ github.head_ref || github.ref_name }}

      - name: Upload packages
        run: node -r esbuild-register .github/prereleases/upload.mjs
