/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./container-app/src/worker-configuration.d.ts -c ./container-app/wrangler.jsonc --no-include-runtime` (hash: 00c134ce4e6653c1a880ff25fc21d95a)
interface InternalEnv {
	CONTAINER: DurableObjectNamespace<import("./index").FixtureTestContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "FixtureTestContainer";
	}
	interface Env extends InternalEnv {}
}
interface Env extends InternalEnv {}
