/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 6a82614a2fd3a4aebf40fdf5a96f7d2b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "AuthSession";
	}
	interface Env {
		AUTH_SESSION: DurableObjectNamespace<import("./src/index").AuthSession>;
	}
}
interface Env extends Cloudflare.Env {}
